### ISSUE TITLE
Try to determine POI on a long click on the map

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#100]
On long click on the map, POI is created but without any information regarding it (except coordinates). Try to fetch this information from the current Nearby provider with the type corresponding to wildcard.

Probably should add new function for such call to each of the providers. If the provider doesn't support such call, return empty result.

**Comment by bertob** [comment]
I'd actually make it a regular tap, not a long tap, since it's much more discoverable.

**Comment by rinigus** [comment]
It may actually work. I was afraid of "false positives" with new POIs created during swiping, but it seems to be not the case. I'll test run single tap a bit for few days and, hopefully, it will work as expected

**Comment by rinigus** [comment]
Tried it and its interfering with double click. Also, single click is useful to keep for regulation of amounts of gui elements shownn on map. Like switching on/off extra elements showing search, zoom levels and such. That's a way  Google Maps allows to clean the interface, for example

**Comment by bertob** [comment]
> Tried it and its interfering with double click

Are you sure? It works fine for me in MapsMe...

> Also, single click is useful to keep for regulation of amounts of gui elements shownn on map. 

I don't quite follow, you mean you'd show/hide some UI elements on single click on the map? How does that look in Google Maps?

**Comment by rinigus** [comment]
Interference can be probably dealt with. But with interaction, that's a different story. I don't have Android device with me, so, I am describing from the top of my head:

* on start, Google Maps (gmaps) show a map and gui elements on  top (search , selection of map layers, compass, scale and such )

* you could clear all elements by single click on a map where you don't have any pin. if you click again, the elements appear.

Similar interaction is on few other apps I have seen, like camera apps. It's intuitive, allows you to have a clear view or all tools in a click, and would be useful in navigation mode as well.

With the respect of navigation mode, that will allow to have  a clean mode with navigation instructions and gui elements only and, if you need, you could switch with a click to the mode with extra controls (map layers, menu switch if it will stay, search and so on).

**Comment by rinigus** [comment]
Filling POI data has been done through introduction of reverse geocoding (8cc7718b3af4cb35085052bc294caedbfebcb03a) and hooking it to creation of POI with a long click (abae93617d4a21a4d912731e2ddc71bd29213a49). We can discuss later whether a single or long click is needed, this is trivial to change. For now, I am closing this issue, since functionality is there
