### ISSUE TITLE
Light theme support

### ISSUE THREAD

**Issue by DylanVanAssche** [rinigus/pure-maps#107]
![screenshot_20181111_001](https://user-images.githubusercontent.com/4999159/48317689-20cfb980-e5f6-11e8-8253-8b447595286e.png)

Light themes in SFOS 3 make it difficult to read the navigation information. Normal ambiences are fine. I think the QML texts are not following the Silica text colors.

**Comment by DylanVanAssche** [comment]
Thanks! No problem, I will be happy to assist you.

**Comment by rinigus** [comment]
We managed to update the port to 3.0.0.8 and I tested my fix. All should work as expected.

**Comment by DylanVanAssche** [comment]
Thanks!
