### ISSUE TITLE
Small gui issue

### ISSUE THREAD

**Issue by eson57** [rinigus/pure-maps#115]
There's not enough space for the test result in Settings/Testing. Maybe you could make it a 2 liner?

I can't seem to find the right command line to start Pure Maps (harbour-pure-maps, pure-maps don't work), so I couldn't check any other languages but Swedish.

![screen_20181205_001](https://user-images.githubusercontent.com/2996154/49495143-54eb7280-f862-11e8-8dcf-158875568a68.png)

**Comment by rinigus** [comment]
Thank you very much for reporting - completely missed it. Should be fixed now.

As for starting, its `sailfish-qml harbour-pure-maps` for Python apps

**Comment by eson57** [comment]
Thanks!
