### ISSUE TITLE
error: runtime/org.kde.Platform/x86_64/5.11 not installed

### ISSUE THREAD

**Issue by yeehi** [rinigus/pure-maps#116]
PureMaps was installed using FlatPak on KDE-neon, Developer Git stable.
The package failed to launch with the following error:

error: runtime/org.kde.Platform/x86_64/5.11 not installed

Browsing /usr/share there is no qml folder.

**Comment by rinigus** [comment]
You somehow managed to install the flatpak without dependencies. How did you install it? Please use flathub provided command. If you used a command from flathub, please list installed flatpak packages . Something clearly went wrong...

**Comment by rinigus** [comment]
any luck with fixing it?

**Comment by rinigus** [comment]
Since there is no further feedback, closing as stale

**Comment by dlopez-akalam** [comment]
I'm having the same issue, I installed flatpak with apt and again with aptitude, in both situations I got the same error when trying to run installed toogl application

**Comment by rinigus** [comment]
did you reboot after flatpak install? please paste output of flatpak run command when you try to start Pure Maps. Also please paste result of `flatpak list`

**Comment by dlopez-akalam** [comment]
Yes I did, I did not install pure-maps but Toggl. As it is the same error, I guess is not a pure-maps issue but a flatpak setup issue. Anyway, here is the error:
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=TogglDesktop.sh com.toggl.TogglDesktop
error: runtime/org.kde.Platform/x86_64/5.14 not installed
```

**Comment by rinigus** [comment]
Then please open it in repos related to toggl.
