### ISSUE TITLE
Policy for temporary POIs

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#118]
Temporary POIs (tmpPOIs) are the ones that are created by application during search, guide (nearby), and when user makes a long press on a map. 

It looks like a current policy used on tmpPOIs is confusing. In particular, long press and checking out address is not expected to leave a trace later on the map. For overview of functionality, current policy is:

* tmpPOI is created every time when user clicks on a search result (search or guide) and its shown on a map

* tmpPOI is created as a response to a long press on a map

* tmpPOIs are persistent on a map unless removed (one by one or using actions listed below)

* tmpPOIs behave like normal (bookmarked) POIs in terms of being listed as POI on POI Page, can be selected on map, will show up as a search result, can be edited and can be bookmarked (going from tmpPOI to the regular one) / unbookmarked, edited.

* all tmpPOIs together with the shown route (if present) are removed if Clean map is selected

* all tmpPOIs are removed from map if user selects "Show all search results" while on a search page (search or guide).

As it is clear from this list, tmpPOIs are used in search and POI interaction. So, any new policy should define these interactions as well. In addition, #117 should be taken into account.

The current policy has been developed over time and has, in part, historical reasons. One of them was an absence of a support for POIs which is currently available.

**Comment by rinigus** [comment]
One possible policy would be:

* On long click (maybe replaced later by regular click), new tmpPOI is created and shown with details. User can bookmark, edit, drive to/from it. If not bookmarked, on exit of tmpPOI view by clicking on empty space on a map or closing a POI drawer on the bottom, tmpPOI is removed.

* During search, while user looks into search results, that search tmpPOIs stay on map. Search mode can be designated by a row on the bottom with the search string. Search mode can be exited by dismissing that string (for example, cross or swiping it off the screen). When search mode is exited, tmpPOIs are all removed.

* tmpPOIs are not saved between program restarts, as they are now. 

Such policy will reduce the role of tmpPOIs, remove ability to combine tmpPOIs over several searches. But maybe its OK and such role will be replaced with the bookmarked POIs

**Comment by bertob** [comment]
The proposed policy sounds good to me

**Comment by rinigus** [comment]
The policy has been implemented and will be a part of the next release.
