### ISSUE TITLE
how to set up for offline maps

### ISSUE THREAD

**Issue by trappedinspacetime** [rinigus/pure-maps#127]
Hi,
First of all, thank you for developing these apps. 
I am running Ubuntu 16.04, I installed `io.github.rinigus.OSMScoutServer` and `flatpak install flathub io.github.rinigus.PureMaps` from `flathub`. I downloaded offline map of Turkey, but I don't know how to set up the client `io.github.rinigus.PureMaps` to request tiles from local `io.github.rinigus.OSMScoutServer`. I need guidance.

**Comment by rinigus** [comment]
That should be relatively simple:

* start the server
* start Pure Maps
* in Pure Maps, go to menu (9 dots at the middle bottom), and choose Offline profile.
* now you should get your data from osmscout server.

in the server you could change logging preferences to info level and should see access to the tiles and other services  by    pure maps.

please let me know if it helped.

**Comment by trappedinspacetime** [comment]
I picked up `offline` mode, I got flood of errors:

      ConnectionRefusedError: [Errno 111] Connection refused
      GET http://localhost:8553/v1/search?limit=25&search=kad%C4%B1k%C3%B6

      [ ERROR ]  "{qmlrunner}[Style]: Failed to load tile 16/38078/24595=>16 for source mapbox: Couldn't resolve host name: Couldn't resolve host 'api.mapbox.com'"

I pasted `http://localhost:8553/v1/search?limit=25&search=kad%C4%B1k%C3%B6` into browser and some `json` formatted results appear.

There may be some `flatpak` container permisson problems?

**Comment by rinigus** [comment]
I presume its Pure Maps output, at least looks like it. 

The fact that you can get JSON reply with the search results is good - this tells that OSM Scout Server works as it should. 

Maybe there is something which prevents communication between two flatpak containers. This would explain connection refused error. 

The style error is probably due to the fact that Pure Maps couldn't load OSM Scout Server map style and it stayed at the one provided by Mapbox. I presume the errors will be different if you start Pure Maps again.

On my platform (Gentoo), communication between different flatpaks works and I can use Pure Maps + OSM Scout Server to get offline maps nicely. I am using Flatpak 1.0.6 (as reported by --version). 

Frankly, I don't know much about flatpak and the used container format. I do wonder if there is some mailing list were we can ask for help.

**Comment by trappedinspacetime** [comment]
Thank you for your help. I restarted both of the applications. I post some of the error messages, they repeats:

      [ ERROR ]  "{qmlrunner}[Style]: Failed to load tile 15/19030/12286=>15 for source mapbox: Couldn't resolve host name: Couldn't resolve host 'api.mapbox.com'"
      [ ERROR ]  "{qmlrunner}[Setup]: loading style failed: Couldn't connect to server: Failed to connect to localhost port 8553: Connection refused"
       convert: QVariant(std::nullptr_t, (nullptr))
       http://localhost:8553/v1/search?limit=25&search=trabzon
       connection to localhost:8553
       failed: ConnectionRefusedError: [Errno 111] Connection refused
       failed:
       (most recent call last):
        File "/app/share/pure-maps/poor/geocoder.py", line 128, in geocode
    results = self._provider.geocode(query, params)
        File "/app/share/pure-maps/geocoders/osmscout.py", line 49, in geocode
    results = poor.http.get_json(url)
        File "/app/share/pure-maps/poor/http.py", line 237, in get_json
    headers=headers)
        File "/app/share/pure-maps/poor/http.py", line 327, in _request_json
    text = _request(method, url, body, encoding, retry, headers)
        File "/app/share/pure-maps/poor/http.py", line 259, in _request
    encoding=encoding, retry=retry, headers=headers)
        File "/app/share/pure-maps/poor/http.py", line 213, in request
    if 'exception' in result: raise result['exception']
        File "/app/share/pure-maps/poor/http.py", line 169, in _request_worker
    headers=task['headers'])
        File "/app/share/pure-maps/poor/http.py", line 287, in _request_real
    connection.request(method, path, body, headers=headall)
        File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
        File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
        File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
        File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
        File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
        File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
        File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
        File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
      : [Errno 111] Connection refused
       convert: QVariant(std::nullptr_t, (nullptr))
       http://localhost:8553/v1/search?limit=25&search=trabzon
       connection to localhost:8553
       failed: ConnectionRefusedError: [Errno 111] Connection refused

**Comment by rinigus** [comment]
This is all consistent with communication error between Pure Maps and OSM Scout Server. Can you please try to enable network on that PC if its disabled.

Also, what flatpak version do you have?

**Comment by rinigus** [comment]
Maybe you could try to update flatpak as well. I presume its coming from PPA anyway...

**Comment by rinigus** [comment]
Any luck with the setup?

**Comment by trappedinspacetime** [comment]
:) thank you for asking, I was keeping checking up any news from you. I forgot to tell you two things:
First, I use 32 bit installation with 64 bit kernel, via debian multiarch support. I run many 32bit and 64bit applications within flatpak environment without problem.
Second, I don't have installed KDE desktop. Ubuntu is based on debian gnu/linux. 
Permission in `metadata` file `xdg-config/kdeglobals:ro` may not  exist in Ubuntu. 
I downloaded the source codes, built and installed each of them respectively `flatpak`,  `xdg-desktop-portal` and `xdg-desktop-portal-gtk` from Github. Flatpak runs well.
OSMScoutServer seems to be running well, PureMaps is runnink well in online mode.
I think PureMap fails to communicate with `localhost:8553`

By the way, what is the shortcut of zooming out in PureMaps?

**Comment by rinigus** [comment]
I would expect that KDE availability should not be that important in this case.

I suspect that there is some kind of firewall preventing TCP/IP communication between flatpaks. Now how to check that is another matter. I am not committing myself to fix it and figure out which permission or limitation is responsible for it, sorry. Let's see who of us will get to it first. 

Shortcut for zooming in and out: none on the keyboard so far. I am using a wheel of the mouse for zoom changes. 

Pure Maps was developed originally for mobile - hence the interaction with the keyboard is poor. At this moment, I am not planning to fix it yet. There is a lot to do before I can get to it.

**Comment by rinigus** [comment]
Excellent! Thank you for letting me know that fast! Enjoy using it...

**Comment by portasynthinca3** [comment]
> AT LAST!!! I found the culprit, it's my `/etc/hosts` file. It was missing `127.0.0.1 localhost` line. I tried many things to fix it in vain. When I was reading `StackOverflow` topics regarding `connection refused` error in localhost, I tried `curl http://localhost.8553` strangely I got `connection refused` error, then it occurred to me checking out `/etc/hosts` file. But my localhost was running well prior to that fix. I used to reach my local chess website via browser. I am sorry that I took your time. If you didn't respond I wouldn't fix it by myself. PureMaps runs very well now. Thank you again for all your help. Regards.

That was the cause of the problem in my case as well! Frankly i find it quite weird. Thank you though!
