### ISSUE TITLE
speed indicator shows only half of real speed

### ISSUE THREAD

**Issue by planetos** [rinigus/pure-maps#130]
Field-testing Puremaps on a Sailfish XA2 device it seems the speed indicator in the lower left corner during navigation-mode only shows half of the real speed. Estimated travel time is correct though. Would it be possible to change this?

**Comment by rinigus** [comment]
Its a bug in XA2 sfos, see https://together.jolla.com/question/196267/xa2-half-gps-speed

I hope it will be fixed in the next SFOS release. Closing.
