### ISSUE TITLE
change the cursor's colour

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#14]
now that you have taken over the development i do assume i can redirect my suggestions/bugs reporting to you, and i start with something i think it's really important...

chang the colour of the cursor...i know it may be stupid but the cursor is blue and the route's line is blue too, it may get confusing from time to time, and on night mode is purple on purple, haven't tested this purple yet but but blue on night mode was even more confusing, so anyway would be nice to have the cursor or the line of another colour...

**Comment by eLtMosen** [comment]
discussing some rough ideas here:
[https://talk.maemo.org/showpost.php?p=1552252&postcount=351](url)

**Comment by rinigus** [comment]
Fixed using Mosen design with increased contrast. Commit 7fc8d1820ac820581ba5cfaebf1e1e6fcb1b3a63
