### ISSUE TITLE
[Feature request] Show basic route info without starting navigation

### ISSUE THREAD

**Issue by zwieberl** [rinigus/pure-maps#141]
I usually use Pure Maps without GPS (I know where I am ;-) ), meaning I search for a route, but don't use navigation (often, because I don't want to go there now, but just to get a rough idea of the route).

When calculating a route from A to B, it would be nice, if basic informations about the route would be shown, without needing to start the navigation, like: 
* Distance
* Estimated duration
* Possible fees (not tested, so not sure if this is already shown)

Would this be possible?

**Comment by rinigus** [comment]
Fees are not known, in terms of money, as far as I understand. But maybe I can retrieve data on whether any toll is included.

As for checking out the route without GPS. Do you see a tiny black strip on the top of the map when you have route displayed?

**Comment by zwieberl** [comment]
Fees are actually not really important for me.
As for the tiny black strip (Pull down menu?): Yes I do have one, but I can't seem to be able to interact with it..

**Comment by rinigus** [comment]
Try to press on that strip, it should bring you to the navigation pages where you could check out the route. (I'll have to test your scenario as well). Does that strip has a number on it? Distance from what-it-thinks-is-your-location to the route?

**Comment by rinigus** [comment]
Can you please provide a screenshot? Sounds rather strange that you have then any strip at all.

**Comment by zwieberl** [comment]
Ok, in the screenshot the strip at the top doesn't show. Maybe I am mistaken (a tiny black strip at the top of a black phone is difficult to see ;-) ), although I switched between the map and menu and could make out a difference between Navigation map and normal map at the top. 

Once I click on "<- Navigation", the bottom pane disappears. Thats all. 
 
![20190106114421](https://user-images.githubusercontent.com/2752876/50735079-0d317100-11a9-11e9-8f55-463f911386b6.png)

**Comment by rinigus** [comment]
OK, there is then a need to change navigation bar on top. I will look into it, let's keep this issue open for it.

**Comment by rinigus** [comment]
I have added total distance and duration when just route is displayed, without navigation. Will be released when the next release will be pushed out
