### ISSUE TITLE
[Feature request] Search in visible area only

### ISSUE THREAD

**Issue by zwieberl** [rinigus/pure-maps#142]
With a lot of maps-data stored, offline-searching for a location (city-name) can take quite long.
Is it possible to only search in the currently visible area to drastically reduce the amount of data being searched? At least I am usually in the rough vicinity of what I am looking for anyways. So I could simply zoom out a bit and search fast for what I was looking for. Otherwise, searching (esp. 2 places for navigation) can take annoyingly long.
This could be represented simply by a checkbox in the search page "only search in the currently visible area".

**Comment by rinigus** [comment]
Are you in UK? UK searches right now are taking way longer that is expected. Its one of the critical issues of OSM Scout Server I will have to address.

One option would be to use Nearby search and provide reference location, radius, state that the type is Any and give a name. Although, that will not allow you to search for address - that needs address expansion.

If search takes too long, can you check whether using a single database in OSM Scout Server for search would help you out?

**Comment by rinigus** [comment]
Search of visible area, as it is, is not expected to be faster due to the way the geo database is organized. In this respect, let's find which offline database makes it slow for you.

**Comment by zwieberl** [comment]
I see. I have more or less complete Europe (excluding Spain) downloaded. 
Deactivating UK- and Ireland-maps does indeed speed up searching considerably. Now it takes roughly 10 sec. to search a city instead of 1+ minute. Still not as fast as I would like it, but not too bad. 
With respect to "single database in OSM Scout Server": I might give it a try, but currently I have no idea how :-)

**Comment by rinigus** [comment]
Single database: 

In OSM Scout Server:

* go to settings
* scroll to geocoder-nlp settings
* disable search all available maps
* accept

On the main screen of OSM Scout Server, you will see a toggle at the top with the currently selected map

**Comment by rinigus** [comment]
The large fraction of the search time is parsing and figuring out what's in your query. This is done once per language/country combination and rather slow for English (probably my bug in training the dataset). Since parsing has to be done anyway for all databases, specifying country doesn't help much.

I would suggest to either stick to a single country (or dataset depending on country) and see how it goes. If you want to search most of EU but not UK, you could unsubscribe from UK in OSM Scout Server for time being. This will not delete anything unless you make a cleanup in Map Manager of OSM Scout Server, but will not be used in active operations.

**Comment by rinigus** [comment]
PS: But on the top of that, I don't think I can do much more about it. Should we close this issue, at least for now?

**Comment by zwieberl** [comment]
Yes, I think we can close it. I will stick with UK deactivated, which gives reasonable results. Thank you!

PS: For this kind of "select only one map" or "deactivate certain maps", it would be nice if countries like Germany and France would also have a "global subscription" instead of 25 separate maps for the individual parts, though.

**Comment by rinigus** [comment]
Have to think how to make such global subscription. Feel free to open an issue for osm scout server. Closing over here.
