### ISSUE TITLE
pinch to zoom got stuck

### ISSUE THREAD

**Issue by planetos** [rinigus/pure-maps#143]
Using Puremaps on a Sailfish XA2 more often I discovered, that sometimes the pinch-to-zoom gesture would not work as expected. I usually run puremaps with OSM scout server. Now, when there is no gps satellite connection (for example indoors), it happens that zooming into a map only works by doubletapping the screen, zooming out would not work. Moving a map however worked fine. So I played around with the auto rotation and auto centering setting, but it made no difference. Even restarting the app did not change this behaviour. But, after a few hours or sometimes a few days, when I restarted the app, pinch-to-zoom was back to normal, even without a satellite fix.

**Comment by rinigus** [comment]
please reopen it if you get convinced that its Pure Maps bug and not of XA2 adaptation of SFOS. I am closing it for now
