### ISSUE TITLE
mapbox night mode

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#15]
i recall whogo maps having a night mode for mapbox default maps, i do remember they where quite unreadable but mapbox default maps are more pleasant to the eyes in respect to the osm ones.

maybe is possible to have mapbox night back with some tweaking to increase readability?

**Comment by rinigus** [comment]
mapbox night mode that I am aware of, is "Mapbox Traffic Night". this one is already supported.

as for readability of osm scout maps - you are welcome to work on styles. although, that's not trivial :)

**Comment by legacychimera247** [comment]
Unfortunately that does not work as streets lines are over the route line so it's not visible at all...

Well thank you anyway :)

Il Giovedì 23 agosto 2018, rinigus scrive:
> mapbox night mode that I am aware of, is "Mapbox Traffic Night". this one is already supported.
> as for readability of osm scout maps - you are welcome to work on styles. although, that's not trivial :)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by rinigus** [comment]
that's right, now I remember. will have to look into it - there is an option to fix route lines

**Comment by rinigus** [comment]
Had some time to look around and, if I understand your issue correctly, its fixed now. The traffic styles show traffic lines above the layer that we used to position route line. I believe that its OK now, after commit last night. If you know how to test it from the source, please do so. Otherwise , we can wait till the next release.

**Comment by legacychimera247** [comment]
This is exactly what i mean, as you may see the line which explain the kind of street completely override the route's line...

Il Giovedì 23 agosto 2018, rinigus scrive:
> OK, I mixed up with something else. What do you mean that the street lines are over the route line? Can you show it on the screenshot and highlight the region?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by rinigus** [comment]
should be fixed with 1.3.0. Please reopen if it is not
