### ISSUE TITLE
Testing: No engine available for selected language

### ISSUE THREAD

**Issue by sfbg** [rinigus/pure-maps#203]
I use Pure Maps, basically since the first releases.

Voice commands have never worked, but as I do not like them much and do not miss them, I file the bug this late.

When testing in Settings, I always get "No engine available for selected language" whatever the selected language or gender.

What am I missing?

**Comment by rinigus** [comment]
Assuming that we talk about Sailfish, you are missing 

https://openrepos.net/content/rinigus/mimic

or

https://openrepos.net/content/rinigus/picotts

Install those and you should be all set for the supported languages. Mimic, for me, sounds better. So, if you prefer English, I would suggest that to try first. PicoTTS has larger number of supported languages. Unfortunately, espeak is rather bad and I would recommend to avoid it.

Let me know here if it helped

**Comment by sfbg** [comment]
Installing Mimic solved the problem for English which is fine for me. Many thanks!

Are those TTS engines always installed separately from Pure Maps? If so, then there should be a more visible hint about this somewhere in the UI, perhaps in the Testing status message.

**Comment by rinigus** [comment]
Its a good point. I have added a note that is shown during testing if the engine is missing. 

As for your question: yes, on Sailfish, TTS engines have to be installed separately. I didn't want to add relatively large packages (mimic for example) as a dependency for Pure Maps. That way users can choose what they prefer for TTS.

Closing the issue. Feel free to continue discussion here and reopen if something has to be addressed in addition.

**Comment by sfbg** [comment]
Thanks. One idea, to make it even more evident, is to disable the "Voice navigation instructions" toggle (and add a hint why) in Preferences -> Navigation, as long as no TTS is installed. Otherwise it looks as if it is a bug, when in fact just a library is missing.

**Comment by rinigus** [comment]
The problem is that it depends on the selected language. I'll think about it.
