### ISSUE TITLE
Add day and night switch

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#21]
Day / Night / Auto?

**Comment by rinigus** [comment]
should be possible, would have to think how

**Comment by carlosgonzz** [comment]
take ur time, due to several features-task in queue.

**Comment by jdrescher2006** [comment]
Hi rinigus, for implementation of automode you could take a look at my app Laufhelden: [https://github.com/jdrescher2006/Laufhelden/blob/master/src/light.cpp](url)

**Comment by rinigus** [comment]
> For implementation of automode you could take a look at my app Laufhelden: 

thanks! I'll have to see how to get it working on QML/python only

**Comment by rinigus** [comment]
Fixed in recent work on map grouping
