### ISSUE TITLE
Fluid movement of Position Marker and Map while navigating

### ISSUE THREAD

**Issue by eLtMosen** [rinigus/pure-maps#229]
Comparing Pure Maps with high end competitors brings to mind that most of them do a transition between known GPS locations and time the map and position markers movement and rotation in such manner that a fluid overall impression of movement is achieved.

Since Pure Maps is currently nicely battery frugal and such a feature could raise energy consumption quite a bit, it might be a good idea to make it optional.

Have there already been attempts to do it? 
Are there any known show stoppers specific to Pure Maps?

**Comment by rinigus** [comment]
I think we even used to have smoother transitions. I will have to look into why did I disabled that... Let's keep issue alive and look into it in future

**Comment by eLtMosen** [comment]
The animation while map rotation and angling is already nicely smooth.
What is missing is a kind of interpolation between the last known gps locations to make the position marker follow the route in a smooth and well timed continous "floating" transition.

**Comment by rinigus** [comment]
We had smooth transitions of map and position that were not matching, I think. As a result, current location was escaping from screen. Will have to look into how to make it properly .

**Comment by eLtMosen** [comment]
Only a short explanation why i need to stress this. From a casual users perspective smooth animations and "real-life" resemblance of activity in the app are a crucial thing. The only negative feedback i receive when showing Pure Maps to family and friends is that they perceive the navigation as "stuttering" and slow performing. (LOL) They comment along the lines "My old In-Car-Nav did that 1 second update also. It is awfully irritating".
I see those comments as a really positive sign. If all casual users are missing is smooth animation, once you pull it off, pure maps suddenly plays in the same league as waze, here and all others from casual users POV.
Oh, and i could totally understand if that is exactly what you want to have much later. Considering casual users storming the APIs and asking stupid questions :)

**Comment by rinigus** [comment]
:) Will do. Probably earlier than later, let me see if I can figure out a formula. Should be relatively easy

**Comment by piggz** [comment]
was about to report the same issue,.glad its already tracked :)
