### ISSUE TITLE
cursor is a little laggy

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#23]
tried pure maps and the app itself works almost fine, the only thing is the cursor lag during the route...if i recall, whogo maps cursor was more fluid...is this something that could be improved or maybe is just the jolla one too slow for all these things on screen?

**Comment by rinigus** [comment]
strange. if anything there is less smoothing in pure maps than in whogo maps during navigation. I have removed map animation in this regime and maybe now you could just see clearer where the location is. There is some lag in position shown, but I am not sure I can do much about it (may come from the system as well).

As a test, try to disable map matching (snap to road), if you have it enabled. Maybe that causes some additional lag on J1?

**Comment by legacychimera247** [comment]
Made a comparison with whogo maps and i must say that even if a little less laggy, the cursor is lagging a little even on whogo maps so it must be a jolla 1 hardware, and disabling snap to road didn't help

I think anyway pure maps should lag a little more than whogo maps since yesterday was my first proper ride with that and the first time i noticed the cursor lagging (even if the map seems fluid, it just seems the cursor is moving block by block)

But in the end if you cannot do more about i'm fine with that :)

Il Sabato 25 agosto 2018, rinigus scrive:
> strange. if anything there is less smoothing in pure maps than in whogo maps during navigation. I have removed map animation in this regime and maybe now you could just see clearer where the location is. There is some lag in position shown, but I am not sure I can do much about it (may come from the system as well).
> As a test, try to disable map matching (snap to road), if you have it enabled. Maybe that causes some additional lag on J1?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by rinigus** [comment]
The movement of the cursor block by block is in WhoGo as well. Its there just masked by animation of the map. Which, at faster speeds, met that cursor could even go out of the map and return back. GPS is usually updated once per second that can lead to such blocky movement. In practice, while you could see such movement, I don't think its major annoyance and we could keep it, at least for now and some future.

Closing this for now
