### ISSUE TITLE
Make position marker to indicate GPS signal strength

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#234]
https://talk.maemo.org/showpost.php?p=1555615&postcount=627
https://talk.maemo.org/showpost.php?p=1555618&postcount=628
https://talk.maemo.org/showpost.php?p=1555648&postcount=631

**Comment by sbridger** [comment]
I will note that filled position markers (627) obscure the map exactly where I want to see it. If they are so small they don't, then I have trouble seeing them in difficult situations (screen moving)

This is worse in the topomap use cases.

**Comment by rinigus** [comment]
This is unfortunate side effect of whatever you want to show on the map. although, this issue is on other topic
