### ISSUE TITLE
App icon grey color not optimal for light ambieces

### ISSUE THREAD

**Issue by sfbg** [rinigus/pure-maps#237]
The light-grey outside color of the icon is often almost identical as the light background of the app grid, when a light ambiance is used, making the icon look strange.

**Comment by rinigus** [comment]
We have just finalized the design of the icon. I admit, its not perfect for light background, but we have to consider that there are probably problematic issues with any icon color selection. At this moment, I would prefer to keep the icon as it is and won't fix this issue. I am closing it here. If you consider that a better solution can be found, please discuss it at TMO.
