### ISSUE TITLE
pure maps unable to calculate certain routes

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#238]
This one might be quite long and quite hard to explain so i will try to be as clear as possible.

I have to go from point A to point B, and i have multiple routes to do so. I have exactly :
Route 1 which can go 1.1 and 1.2 at a certain point, and
Route 2 which can go 2.1, 2.2 and 2.3

Now, i start from point A and Pure Maps give me route 1.2 despite not being the fastest. On the middle of the route i come to the turn where i can choose  if go to route 2 or continue on route 1, i take route 2 and then head to 2.3 considering is the fastest route. Unfortunately pure maps recalculate the route insisting on turning back and take route 1 again, and this, till i get on a turn where i can choose if going 2.1 or 2.2/2.3 where he tells me to go 2.1. I head towards 2.2/2.3 and despite fastest route is selected and despite is not the fastest, pure maps suggest me to go 2.2 and this until i am on 2.3 where it finally calculate 2.3

Now the first question is : why poor maps insist on telling me to turn back to route 1 even if i'm already on route 2?

And the second : why is unable to calculate 2.3 untill i am in there?

Hope i was as clear as possible :)

**Comment by rinigus** [comment]
Assuming that you used OSM Scout Server (offline) or Stadia Maps (online) for router calculations. You will have to open an issue at https://github.com/valhalla/valhalla/issues and provide specific example (with GPS coordinates) for them to be able to test and assert the routing. 

OSM Scout Server is currently using Valhalla 2.6.3. This is somewhat older release and would have to be mentioned in your issue. I don't know what's Valhalla's version used by Stadia Maps.

As Pure Maps is just showing and following routes, I am closing an issue over here.

**Comment by legacychimera247** [comment]
don't know if it may interest yo, but i have written valhalla devs and they are saying that this problem is due to app not having a route selection, anyway you can follow the discussion here...

[https://github.com/valhalla/valhalla/issues/1766](url)

**Comment by rinigus** [comment]
Thank you very much for heads up, I will check it out
