### ISSUE TITLE
Pure maps (flatpak) crashes when I push buttons

### ISSUE THREAD

**Issue by carmenfdezb** [rinigus/pure-maps#239]
Hi rinigus!!
I've installed Pure Maps in my tablet-PC with Fedora 29 via flatpak and it works really nice. I have no problems if I use the mouse and click on buttons; however if I push buttons with my fingers, app crashes and I get an error: qmlrunner closed unexpectedly. How can I solve this problem?

**Comment by rinigus** [comment]
Try to check if its general issue for qml apps on flatpak. Although, I don't know which app to use for testing

**Comment by rinigus** [comment]
Hi @carmenfdezb ,

do you still have this issue?

**Comment by carmenfdezb** [comment]
Yes, and I don't know how to solve it. qmlrunner crashes because of next error: No segments found in coredump './coredump'

**Comment by rinigus** [comment]
Have you tried to update all flatpaks? Its a mystery, I must say

**Comment by carmenfdezb** [comment]
I tried unistall and install again, but it doesn't work. On the other hand, I didn't have any problem in some old version of Pure Maps, the first time I install Pure Maps in my PC (I don't remember what version was)

**Comment by carmenfdezb** [comment]
The issue is only happening when I use touch screen, using mouse everything is working really nice :)

**Comment by rinigus** [comment]
Does it happen to any other app in flatpak? Did you try to make `flatpak update`?

**Comment by carmenfdezb** [comment]
I've done `flatpak update`, but it doesn't solve this problem. I've installed spotify via flatpak but it works fine using touch screen

**Comment by rinigus** [comment]
Try to add KDE flatpak environment 

```
flatpak remote-add --if-not-exists kdeapps --from https://distribute.kde.org/kdeapps.flatpakrepo
```

and install `org.kde.kirigami2.gallery` from kdeapps. See if that works.

To my knowledge, I don't have anything in the code that is touch specific. So, it should be some bug in the used libs. Question is which.

**Comment by carmenfdezb** [comment]
I've tried your last instructions, but it doesn't work.
I've analized coredump file and it says '/app/bin/qmlrunner: No such file or directory.'. Is it possible that qmlrunner is missing in my PC? I don't know what to think

**Comment by rinigus** [comment]
`/app/bin/qmlrunner` is inside flatpak, available only via flatpak tree. 

what didn't work from my instructions regarding kirigami2.gallery installation?

**Comment by carmenfdezb** [comment]
Sorry, I meant that `org.kde.kirigami2.gallery` didn't solve my problem

**Comment by rinigus** [comment]
But does Gallery crashes the same way or is it stable to touch?

**Comment by carmenfdezb** [comment]
No, it doesn't crash. I can run org.kde.kirigami2.gallery and use it without any problem.

**Comment by rinigus** [comment]
I see. Thanks! This problem occurs only while you browse the map or in some other elements as well?

**Comment by carmenfdezb** [comment]
I can browse the map, the app only crashes when I tap on any button (menu, center position...)

**Comment by rinigus** [comment]
one more test (and sorry for the gaps with debugging): can you swipe out the menu from the left? just swipe from the left border to the center - this should bring out menu. can you press buttons on that menu?

**Comment by carmenfdezb** [comment]
Sorry for the late answer. If I access to left menu (swipe from de left border) I can press any button and the app doesn't crash.

**Comment by rinigus** [comment]
Interesting. I'll think how to make test builds for you

**Comment by rinigus** [comment]
Sorry for slow feedback. Try to delete https://github.com/rinigus/pure-maps/blob/48a48ca59ab29034f62e49b6a43be43f2b835b86/qml/MapButton.qml#L44 and the next lines with `layer`: so, between L44 and L50, included. Maybe these graphical effects are causing it to crash

**Comment by carmenfdezb** [comment]
> Sorry for slow feedback. Try to delete
> 
> https://github.com/rinigus/pure-maps/blob/48a48ca59ab29034f62e49b6a43be43f2b835b86/qml/MapButton.qml#L44
> and the next lines with `layer`: so, between L44 and L50, included. Maybe these graphical effects are causing it to crash

That solved my problem!! Thank you so much!!

**Comment by rinigus** [comment]
Very strange still. I wonder if its some error in graphical stack of your device...

**Comment by TimMagee** [comment]
I have the exact same bug on KDE Neon on a Dell Laptop.

**Comment by rinigus** [comment]
Have you tried the same fix?

**Comment by TimMagee** [comment]
I am having trouble with the build process. I get the following error message:

`$ make flatpak-build`
`make: *** No rule to make target 'flathub-install-kirigami'.  Stop.
Error: module pure-maps: Child process exited with code 2
Makefile:75: recipe for target 'flatpak-build' failed
make: *** [flatpak-build] Error 1`

**Comment by rinigus** [comment]
I am retesting the build system. Meanwhile, you can install Flatpak from Flathub using `--user` keyword during installation, go to the folder with the app (my case follows):

```
.local/share/flatpak/app/io.github.rinigus.PureMaps/x86_64/stable/active/files/share/io.github.rinigus.PureMaps/qml/MapButton.qml
```

and edit it there. Save and run again. I would expect that all will work as it should. Which brings the question - why doesn't it work with the shadow?

**Comment by TimMagee** [comment]
For me removing line 44 
> https://github.com/rinigus/pure-maps/blob/48a48ca59ab29034f62e49b6a43be43f2b835b86/qml/MapButton.qml#L44
solved the problem even with removing lines 45-50.

**Comment by rinigus** [comment]
Would you mind testing with changes in shadow through changes in its radius. As in 

```
        layer.enabled: true
        layer.effect: DropShadow {
            color: styler.shadowColor
            opacity: styler.shadowOpacity
            radius: item.pressed ? 1 : styler.shadowRadius
            samples: 1 + radius*2
        }
```

I wonder whether changes in shadow radius would crash an app as switching off the layer.

**Comment by TimMagee** [comment]
That works for me.

**Comment by rinigus** [comment]
Then I include this in the next release. Thank you!

**Comment by rinigus** [comment]
@carmenfdezb, if you can - please test as well

**Comment by rinigus** [comment]
@TimMagee , what about this:

```
        layer.effect: DropShadow {
            color: item.pressed ? "transparent" : styler.shadowColor
            opacity: styler.shadowOpacity
            radius: styler.shadowRadius
            samples: 1 + radius*2
        }
```

Would that work?

**Comment by carmenfdezb** [comment]
> @carmenfdezb, if you can - please test as well

Hi @rinigus! That work for me:
```
        layer.enabled: true
        layer.effect: DropShadow {
            color: styler.shadowColor
            opacity: styler.shadowOpacity
            radius: item.pressed ? 1 : styler.shadowRadius
            samples: 1 + radius*2
        }
```

**Comment by carmenfdezb** [comment]
> @TimMagee , what about this:
> 
> ```
>         layer.effect: DropShadow {
>             color: item.pressed ? "transparent" : styler.shadowColor
>             opacity: styler.shadowOpacity
>             radius: styler.shadowRadius
>             samples: 1 + radius*2
>         }
> ```
> 
> Would that work?
That works for me too :)

**Comment by rinigus** [comment]
@carmenfdezb: Great!

**Comment by rinigus** [comment]
I expect that the committed fix will be sufficient for the both of you. Its using "transparent" color solution
