### ISSUE TITLE
maps other than osmscout are not working sometimes

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#24]
well the title explains it all, sometimes i select other maps from the menu and to see them properly i need to restart the app, this while in whogo maps they were working well...

**Comment by rinigus** [comment]
please try to start from the terminal using 

```
sailfish-qml harbour-pure-maps
```

and paste if you see some errors from Python while you fail to see some maps. I wonder if it's just filling up some caches or there is a bug

**Comment by legacychimera247** [comment]
Everything seems to work now, the only thing is, if i am not connected to the internet i get a

"Couldn't resolve api.mapbox.com" message on the terminal but i don't think it's related to the issue...

Il Sabato 25 agosto 2018, rinigus scrive:
> please try to start from the terminal using
> sailfish-qml harbour-pure-maps
> 
> and paste if you see some errors from Python while you fail to see some maps. I wonder if it's just filling up some caches or there is a bug
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by rinigus** [comment]
Name resolution issue is expected and should be OK. Please reopen if you get the issues again

**Comment by legacychimera247** [comment]
Nice to hear :) i've started even a complete remapping of my region, to avoid those problem less :)

Il Sabato 25 agosto 2018, rinigus scrive:
> Name resolution issue is expected and should be OK. Please reopen if you get the issues again
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla
