### ISSUE TITLE
pure maps is unable to find some adresses unless exactly typed

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#240]
well the title pretty much explain everything, but i'll give you some examples

i have (example) "london" and "tower of london", and if i put london on the search bar i only get london, if i put tower london i get no results. To have tower of london i need to input exactly tower of london, which is inconvenient, especially with long names or when you know only a part of the name.

**Comment by rinigus** [comment]
For now, try to use "tower london". That should be parsed as a house named tower in london. But the issue is a correct one and I will have to look into it. While its not of Pure Maps, but of the used geocoder (I assume its OSM Scout Server), let's keep it open here for now.

**Comment by legacychimera247** [comment]
ok, thanks

**Comment by sbridger** [comment]
a similar issue is that you have to use "Rd" or "Road" etc exactly as the map has it. It does not know the synonymous abbreviations

**Comment by rinigus** [comment]
As it is OSM Scout Server issue, opened it there and closing here
