### ISSUE TITLE
[Question] Shouldn't Valhalla be also offered as routing engine, when it is active alongside libosmscout? 

### ISSUE THREAD

**Issue by Olf0** [rinigus/pure-maps#241]
While slowly pursuing my quest for comparing the speed (especially when routing) of PureMaps & OSM Scout Server, OSMand and Maps(.me) running fully offline (on the same SFOS device), I observed that I only have libosmscout available as offline router (plus two GPX options), but not Valhalla. 

OSM Scout Server settings:
- Profile: Custom (to serve  bitmap and vector map clients)
- Selected backends: libosmscout, Valhalla, geocoder-nlp with libpostal (in *Settings*), plus MapboxGL and these in *Map manager: datasets*

But PureMaps only offers libosmscout as routing engine in PureMaps' *Navigation -\> \<top pulley\> Using XXX* (plus GPX and GPX Smart), but not Valhalla.
Side note: This is easier to see, when PureMaps is in *Offline mode*, but also the case in *Mixed mode*.

OSM Scout Server's log on startup always nicely includes a "INFO: \<time\> Valhalla routing engine started" (right after the usual warning about elevation tiles).

Testing environment: PureMaps 1.1.9, OSM Scout Server 1.1.3 (but IIRC also earlier versions of both) on a Jolla 1 with SFOS 2.2.1 and an Xperia X with SFOS 3.0.2 

Shouldn't PureMaps' *Navigation -\> \<top pulley\> Using XXX*    also offer Valhalla (in addition to libosmscout, GPX and GPS Smart) when both (Valhalla and libosmscout) are active and available per OSM Scout Server?

**Comment by rinigus** [comment]
This is unfortunate confusion. Pure Maps, actually, does not know what OSM Scout Server is using for routing. The server provides HTTP API for routing and Pure Maps is just using it to request a route. So, in Pure Maps menu we have not _libosmscout_, but _OSM Scout_ standing for _OSM Scout Server_. _Server_ is missing from the name since all other services would then have it as well (I presume that's a reason the service was called as this in Poor Maps). 

Now, when the call is received by OSM Scout Server, it will choose the actual router according to your settings. If you selected Valhalla for routing (in Settings or using Profile) then it will be Valhalla. As such, it never has Valhalla and libosmscout routers active at the same time.

**Comment by rinigus** [comment]
PS: Thanks for this stats - looking forward to see it.

**Comment by Olf0** [comment]
Thanks for resolving my confusion: It all makes sense to me, now.

Hence my "real question" supposedly is:
Why can't one select between Valhalla and libosmscout in OSM Scout Server's *Settings: Routing Engine*, if data for both is selected in *Map manager: Storage settings* (and consecutively downloaded) when using *Profile: Custom*?
But as the more advanced one of the two offline routing engines is the currently only selectable one, when both are installed, I now see that this is a minor issue (i.e., rather just a bit inconsistent).

I also understand that this should have been filed at OSM Scout Server's issue tracker, but maybe my rectified question is also easy to answer, hence I currently refrain from opening an issue for this there: as: [Question] Shouldn't libosmscout be also offered as routing engine, when it is active alongside Valhalla?

**Comment by rinigus** [comment]
> Why can't one select between Valhalla and libosmscout in OSM Scout Server's Settings: Routing Engine, if data for both is selected in Map manager: Storage settings (and consecutively downloaded) when using Profile: Custom? Only Valhalla is offered and selectable there.

you can. When you disable Valhalla, libosmscout is used. Its similar to selection of Mapnik and geocoder. Not very intuitive, despite help strings next to these options, as I can see...

**Comment by Olf0** [comment]
Oh, I see that it technically does what I expected, but the graphical representation of these three settings ("router: Valhalla vs. libosmscout", "bitmap maps: Mapnik vs. libosmscout" and "geocoder: geocoder-nlp vs. libosmscout) can be easily misinterpreted:
It is unexpected (at least for me) that one has to simply switch off Valhalla rsp. Mapnik rsp. geocoder-nlp in order to use libosmscout.  I would have expected some kind of chooser to actively set one of the two choices (for these three  settings: router, geocoder and bitmap map provider), e.g. two mutually exclusive radio buttons or a drop down list with two entries.

But the current graphical representation of these settings is compact and logically O.K. (if one understands this settings logic), hence complicating it technically to make it easier to understand that one makes a choice between two options is not worth the effort IMO.

Turning to the settings' current  description, I now understand that their weakness is that they state: 
      `This server allows you to choose between the two X: Y and libosmscout`
      `<radio button> Use Y as X`
      `When selected Y will be used as X [...]`

The first line does not make obvious that libosmscout is the default, thus used when the radio button is deselected.  Specifically "to choose **between**" is a bit misleading as a radio button provides a single "on / off" choice, but not a selection between two options (linguistically, but logically it does).
Furthermore the last line quoted ("When selected [...]") does not state what is set when the radio button is deselected.

Enhancing these strings is a task, which I may try to accomplish, someday.
