### ISSUE TITLE
[Feature request] Option to show altitude lines

### ISSUE THREAD

**Issue by zwieberl** [rinigus/pure-maps#242]
Not sure if this is even possible, but I use pure maps for hiking a lot and it would be awesome to have the option to show altitude / contour lines.

**Comment by rinigus** [comment]
Its possible - I "just" have to add that to the import scripts for offline maps. Will come as a part of https://github.com/rinigus/osmscout-server/issues/304

**Comment by zwieberl** [comment]
A brilliant, I haven't seen that ticket. Thats exactly what I was asking for. 
You can close this issue as a duplicate if you like.

**Comment by rinigus** [comment]
Closing it over here - will keep under OSM Scout Server
