### ISSUE TITLE
Navigation: Option to search only bookmarks

### ISSUE THREAD

**Issue by zwieberl** [rinigus/pure-maps#243]
It probably belongs loosely to either #106 or #139, but I couldn't decide, so I create a new issue for this.

**Feature request:**
When creating a new route, I very frequently go from either the current position to a bookmark or from a bookmark to a bookmark. 
It would therefore be nice to have in the To/From Search page a combobox to be able to search for either only bookmarks, only non-bookmarks or both.

If selected "only bookmarks", it should basically show the bookmark-search page (show all bookmarks to scroll through + a search field).

**Reasoning:**
I know in the current behavior bookmarks go to the top of the search, but unfortunately, sometimes its hard to remember with what letters a specific bookmark started. Being able to quickly scroll through them would be awesome.

**Comment by rinigus** [comment]
I'll have to think about it. Right now, you could type any letter from the bookmarked poi and get it in the list. So, it doesn't have to be the first letter.

The main issue that I see is addition of some selection element to already busy list. Any good UI design for it?

**Comment by zwieberl** [comment]
I understand the problem. 
It could either be a very small combobox next to the search-field (Row), with only icons or 1-2 letters. 
Or a Row of 2 checkboxes saying "[x] Bookmarks", "[x] General search".
Or another page on the page-stack, which goes directly to the bookmark-search, and replaces the current search page (the pageheader would then have to be adjusted to say the going left gives you bookmarks)

**Comment by rinigus** [comment]
I have fixed #106 and added shortlisted bookmarks to the routing page allowing you to choose them fast. After the next release, let's see if you would still feel that this issue needs to be resolved. BTW, on Bookmarks page, you could search for a bookmark and then select "route to" it.

**Comment by Pohli** [comment]
Also related to #81. I usually prefer to scroll through bookmark list instead of typing some letters to find the right bookmark, too.

**Comment by rinigus** [comment]
@Pohli: but then you could just use bookmark page and start routing from there, right?

**Comment by Pohli** [comment]
Yes, if I remember to do so. ☺

**Comment by rinigus** [comment]
with the latest release out, is it still suggested? I would propose to close the issue and keep GUI as simple as possible, without functionality accessible via too many dialogs

**Comment by zwieberl** [comment]
Fine with me! 
Didn't know about the "workaround" for going to bookmarks first and start routing from there, before opening this issue. 
In principle it does exactly what I want, I just have to rewire my brain now. 
Thanks!

**Comment by rinigus** [comment]
Thanks! Closing
