### ISSUE TITLE
empty button

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#255]
simply enough i found an empty button, if you click on a result the panel is empty as you can see...

**Comment by legacychimera247** [comment]
ok, the image didn't upload but if you long tap on a search result you'll see the empty panel (or button) appearing, maybe it can be used to set places as favourites?

**Comment by rinigus** [comment]
Its there for stupid technical reasons, but your idea would make it useful. Thank you, I will look into it.

**Comment by rinigus** [comment]
Since this page is available via search and routing, I disabled the empty button. to add some functionality there could be confusing and I opted for fixing the original issue instead. Thanks for reporting it
