### ISSUE TITLE
Allow map rotation by compass

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#260]
Suggested in view and followMe modes

See http://talk.maemo.org/showpost.php?p=1557461&postcount=705

**Comment by sbridger** [comment]
adding a few more:
[compass on bike](http://talk.maemo.org/showpost.php?p=1559790&postcount=839)
[tristate button](http://talk.maemo.org/showpost.php?p=1559798&postcount=842)
[calibration](http://talk.maemo.org/showpost.php?p=1559915&postcount=852) 
Mentions compass current drain. Magnetic sensor chips are very low power sensors, so would need to test real current drain before assuming that this is true. 
Magnetic compass calibration also needs to consider magnetic declination (20degrees here now)

**Comment by rinigus** [comment]
Looking into how to implement it and already first simple tests are very encouraging. Would have to include https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml? into Pure Maps, as we have location data available as well.

**Comment by rinigus** [comment]
Limiting the issue to compass support, no orientation by hand. If there is an interest in hand-based orientation of the map, open issue separately.

**Comment by rinigus** [comment]
Now just need to add magnetic declination calculations. Looks like have to get some extra lib for it as Qt Position supports it from 5.4

**Comment by rinigus** [comment]
Implemented rotation by compass, closing.

**Comment by sbridger** [comment]
Entering compass declination manually is also OK.
I will test as soon as there is a release for me to test.

Sadly the XA2 sfos gps and compass performance is practically unusable.

The major issue for me is that the GPS will get a lock under clear sky, unreliably in a car, and simply cannot get a lock at all under moderate tree cover (over a 1/2 hour period -zero positions. It does get enough signal to get ephemeris or maybe its using network, as it shows satellite plot). (sfos3.3)

By comparison my winphone 640 locks in 5 seconds with no network in the same positions.

A secondary issue is that the compass drifts terribly (3.2, haven't tried with 3.3 yet), and was unusable. I added declination to the compass app, but didn't do more with it when I found how much it drifted.

**Comment by rinigus** [comment]
On my device, lock may take some time, but when locked it seems to work fine. Compass works quite well too. Note that for compass, I have developed new hardware adaptations which are submitted for review and, hopefully, will be merged in the near future. I hope it will help XA2 as well
