### ISSUE TITLE
Unclear how to install for development

### ISSUE THREAD

**Issue by dcz-self** [rinigus/pure-maps#265]
I tried installing Pure Maps to check out the status on the desktop. It goes OK when following the Makefile, and the Flatpak manifest helps a little, when combined with trying to force the program to run.

The Makefile helps with general installation. Running the binary gives some hints regarding the modules that are missing, which can then be found in the Flatpak manifest. So far, I got that `Nemo.Dbus` needs to be installed with

```
qmake
make
make install INSTALL_DIR=$PREFIX
```

and that the resulting installation can be run using

```
LD_LIBRARY_PATH=$PREFIX/usr/lib QML2_IMPORT_PATH=$PREFIX/usr/lib64/qt5/qml $PREFIX/bin/pure-maps
```

I did get a blank window, and then promptly stack, as the runtime errors are not clear:

```
$ LD_LIBRARY_PATH=install/usr/lib QML2_IMPORT_PATH=`pwd`/install/usr/lib64/qt5/qml PATH=$PATH:`pwd`/qmlrunner ./install/bin/pure-maps 
Current locale: en_US
Translation not found
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Failed to create Geoclue client interface. Geoclue error: org.freedesktop.DBus.Error.ServiceUnknown
file:///foo/install/share/pure-maps/qml/Config.qml:107: TypeError: Cannot read property 'auto_complete_geo' of undefined
file:///foo/install/share/pure-maps/qml/Config.qml:107: TypeError: Cannot read property 'auto_complete_geo' of undefined
^C
```

It looks like the `poor` module failed somewhere, but seeing how it only manages configuration, there's probably another failure.

Here's my issue: it would be nice to have some list of dependencies. I suspect that Osm Scout Server is necessary to get any output, but it doesn't get mentioned in the readme. Flatpak lists `mapbox-gl-qml`, but the binary doesn't complain, and the readme from that project shooes me away by recommending the official Mapbox plugin if I'm using Qt > 5.9, leaving me somewhat confused.

I'm willing to test suggestions and gather them in a MR, perhaps as a `HACKING.md` file.

**Comment by rinigus** [comment]
@dcz-self: thank you very much for opening this issue! I will be able to address it in two days, after coming back from a trip. 

As such, OSM Scout Server is needed only for offline mode. Mapbox GL QML plugin is needed, Pure Maps is build on the basis of it. The note that you refer to is regarding other projects who would consider using Mapbox GL QML, should be considered as a warning. Note that I maybe will remove it and explain the strengths and weaknesses to help to select official (QtLocation) or unofficial (Mapbox GL QML) bindings in future.

As for starting command, I would presume it will be more along lines

```
qmlrunner -P ./install -path /usr/local/lib64/qml pure-maps
```
 
Sorry for incomplete reply, will be able to fully address it in few days

**Comment by rinigus** [comment]
@dcz-self : I have expanded README and restructured it a bit to help you to find the information.

In addition to commit c222dcc, changes are done in 4a914ee916783faef4b7f60d2dd38d2043b3ceae as well (a link was missing). So, try to follow README sections "platform", "dependencies" and "running". These should provide sufficient information. Please let me know how it went.

**Comment by dcz-self** [comment]
On Thu, 20 Jun 2019 10:58:42 -0700
rinigus <notifications@github.com> wrote:

> @dcz-self : I have expanded README and restructured it a bit to help you to find the information.
> 
> In addition to commit c222dcc, changes are done in 4a914ee916783faef4b7f60d2dd38d2043b3ceae as well (a link was missing). So, try to follow README sections "platform", "dependencies" and "running". These should provide sufficient information. Please let me know how it went.
> 

Thank you! I will take a look again as soon as I have the time (it may take a while though).

**Comment by rinigus** [comment]
I have also added instructions on how to use `flatpak-*` targets for development. 

Closing the issue, please reopen if something is still not clear
