### ISSUE TITLE
Add full support for HERE

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#275]
With introduction of profiles, we can now add full HERE support and comply with their license.

- [x] Add more or less full set of map tiles - these can be used outside of HERE profile
- [x] Search
- [x] Search autocomplete
- [x] Reverse geocoding
- [x] Routing
- [x] Re-routing

**Skipped:**

- Search along route: will be added after #261 
- Nearby: is covered by Search

**Notes:**

As Nearby is mostly (except search along route) covered by Search, use default guide for now instead. Work on #261 to add "Search along route" functionality. 

Vector tiles would be nice to get working, but would require designed styles. Maybe someone will want to work on it.

**Comment by rinigus** [comment]
If we start with HERE, see their API first. We need search (address->coordinates), routing and reverse search (coordinates->address).

Pure Maps uses REST API to communicate with the servers. So, check their REST API and see if you can get trucks support if you use it.

Docs are at https://developer.here.com/documentation

Routing at https://developer.here.com/documentation/routing/dev_guide/topics/request-a-simple-route.html

If routing seems OK, then let's start with search. Its API at https://developer.here.com/documentation/geocoder/dev_guide/topics/what-is.html

That API we will translate to code in https://github.com/rinigus/pure-maps/tree/master/geocoders , so Pure Maps will understand it

**Comment by rinigus** [comment]
Looks like HERE has also vector tiles: https://developer.here.com/documentation/vector-tiles-api/dev_guide/index.html

Not sure how to use it, if there are styles available already, and if there is traffic layer there

**Comment by ddobrev** [comment]
You've [mentioned](https://github.com/rinigus/pure-maps/issues/537#issuecomment-823224541) HERE's ready save for searching. Would you have an idea how much work/time it would take to have it? I've tested its searching in HERE WeGo and so far I've found it excellent which means it would be a priceless to PureMaps.

**Comment by ddobrev** [comment]
I can also confirm we need routing because between certain 2 locations HERE WeGo gives me 3 choices while PureMaps only 1 with any settings. I would appreciate some time-line for this as well.

**Comment by rinigus** [comment]
Re geocoding: it shouldn't be too hard, as long as someone reads their API and creates geocoder file. This should be done first as it is rather simple and is used by router anyway.

Re multiple route selection: this is not implemented and will require bit larger work. Again, API reading is needed and implementing the router.

**Comment by ddobrev** [comment]
Sounds we're going to have even purer maps reasonably soon. 🙂 Looking forward.

**Comment by rinigus** [comment]
That would all depend on whether someone will step in and make it. I will be able to help, but there will be some time before I can start implementing this

**Comment by ddobrev** [comment]
Unfortunately, my own open source keeps waiting. So far I can only offer moral support and the promise I'm going to delete Google Maps in favour of Pure Maps once it can find what I need through HERE.

**Comment by ddobrev** [comment]
@rinigus you're absolutely amazing! Now if you could please just focus on https://github.com/rinigus/pure-maps/issues/58, I'm dropping gulag maps and never looking back! Yay, we're going to have a fully functional native solution!
