### ISSUE TITLE
No icons when open map selection from map screen

### ISSUE THREAD

**Issue by atlochowski** [rinigus/pure-maps#291]
No icons when open map selection from map screen
https://www.dropbox.com/s/ald78oi337q1kkr/Zrzut_ekranu_20190731_001.png?dl=0

**Comment by rinigus** [comment]
No, these are absent, indeed. I hope that someone from the community will draw those

**Comment by rinigus** [comment]
Description for requested icons at http://talk.maemo.org/showpost.php?p=1558484&postcount=774

**Comment by rinigus** [comment]
List of missing icons:

Requested icons are as follows:

Type:

- default - default map, as Mapbox Streets
- terrain - map with the focus on terrain, as Mapbox Outdoors
- satellite
- hybrid - satellite with streets
- preview - map used to preview the road before starting navigation
- traffic - same as preview, but with traffic data
- guidance - map optimized for showing while you navigate

Light:

- day
- night

Transport:

- car
- public transport
- walking

All icons are expected to be shown at about 6mm x 6mm sizes on the phone.

**Comment by rinigus** [comment]
Missing icons added, closing
