### ISSUE TITLE
Port to UBPorts

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#294]
For running on UBPorts, we will need to create an environment with several extensions. They are well described in https://github.com/flathub/io.github.rinigus.PureMaps/blob/master/io.github.rinigus.PureMaps.json (Flatpak format), with at least one not really needed anymore (skipping it from the list below).

Those are "must" have
* nemo-qml-plugin-dbus
* mapbox-gl-native-qt - we will use https://github.com/rinigus/pkg-mapbox-gl-native
* mapbox-gl-qml - https://github.com/rinigus/mapbox-gl-qml

Nice to have:

* mimic1 - https://github.com/MycroftAI/mimic1 (for TTS spoken instructions)
* qmlrunner - https://github.com/rinigus/qmlrunner (maybe no need)

Already should be available:

* pyotherside
* Kirigami

Out of these, mimic and qmlrunner are executables. Mimic should be in path, but it can be replaced with flite if its available. If we choose to use qmlrunner - it will be the executable instead of qmlscene in desktop file.

As for main QML plugins:

Nemo DBus is by itself and provides DBus API for QML

mapbox-gl-qml is a plugin that shows the map. On Sailfish, I link mapbox-gl-native-qt statically with that plugin. With Flatpak, I have a luxury to distribute the lib together with plugin - so I use dynamic linking.

Pure Maps frequently is using the latest Kirigami version, sometimes with unreleased features. Would be good to know which Kirigami version is available at the platform.

I wonder, what's common tree of files that is installed by click package? Maybe someone could just list one as an example?

**Comment by jonnius** [comment]
Have a look at [Clickable](https://clickable.bhdouglass.com/en/latest/), the recommended build tool for Ubuntu Touch. It lets you build some template apps, too.

**Comment by rinigus** [comment]
I have added UBPorts platform. To use it, clone the repository (with submodules) and then

```
make platform-ubports
make PREFIX=/<insert_here_prefix> app INCLUDE_GPXPY=yes install
```

If needed, `DESTDIR` option is available as well.

At this moment, Pure Maps should comply with available Qt (5.9) and would "just" require packaging. If some scripts need to be adjusted (such as executable or .desktop), we can add them into `packaging/ubports`  and then install these during `make install`, as done for flatpak.

**Comment by jonnius** [comment]
Are you sure about the `app` target in the command? I can't see one in the Makefile...

**Comment by rinigus** [comment]
Since we don't need to compile anything, there is no such `app` target in Makefile. But the script `pure-maps` is installed in `bin`. 

We may need to adjust that script. Under Wayland, I have to give Qt option `-platform wayland` as well to `qmlrunner`. Not sure what's the state is under UBPorts.

**Comment by mattbel10** [comment]
Hi @rinigus I'm trying to package pure-maps using cmake instead. I downloaded the dependencies you indicated and I'm trying to compile those with qmake. For 'pkg-mapbox-gl-native' I got few fatal errors related to .cpp files. Here the log to see what's going on: [error log](https://paste.ubuntu.com/p/ysKpZpW77C/).
Thank you.
Matteo

**Comment by rinigus** [comment]
Hi Matteo:

Please compile pkg-mapbox-gl-native using `qmake` and this PRO file: https://github.com/rinigus/pkg-mapbox-gl-native/blob/sfos/mapbox-gl-native-lib.pro . That PRO file has to be copied into the mapbox-gl-native folder of the pkg-mapbox-gl-native . For SFOS, I am making it during early of the build process. For Fltapak, the same is done at https://github.com/flathub/io.github.rinigus.PureMaps/blob/master/io.github.rinigus.PureMaps.json#L79

I would suggest to start with qmake and this approach. Later we will all switch to cmake - as soon as Mapbox GL Native build system will get updated.

Rinigus

**Comment by rinigus** [comment]
PS: Note that the version I composed for Sailfish is somewhat different from the classical Qt version. In particular, its using CURL and SSL libs oputside of Qt. This was due to some bugs in Qt that were not going to be fixed in Sailfish. For you, it maybe wise to make a slightly different build with all Qt parts used as they should be. This was done in Debian version of the packaging scripts, as in https://github.com/rinigus/deb-qmapboxgl . 

In general, Mapbox GL Native is the messiest part of all this packaging. If you can, stick to the pkg-mapbox-gl-native first, and later we will evolve to something less hacky

**Comment by rinigus** [comment]
Closing here - main part of the port is done. File specific issues as needed
