### ISSUE TITLE
Pyflakes fails with invalid syntax

### ISSUE THREAD

**Issue by jonnius** [rinigus/pure-maps#296]
I simply tried to run `make` and I get:

```
make
pyflakes geocoders guides poor routers
poor/util.py:118:45: invalid syntax
    print("Failed to detect CPU count", file=sys.stderr)
                                            ^
poor/router.py:113:42: invalid syntax
            print("Routing failed:", file=sys.stderr)
                                         ^
poor/__init__.py:28:15: invalid syntax
          file=sys.stderr)
              ^
poor/config.py:303:27: invalid syntax
                      file=sys.stderr)
                          ^
poor/guide.py:76:47: invalid syntax
            print("Autocomplete failed:", file=sys.stderr)
                                              ^
poor/application.py:85:23: invalid syntax
                  file=sys.stderr)
                      ^
poor/geocoder.py:83:47: invalid syntax
            print("Autocomplete failed:", file=sys.stderr)
                                              ^
poor/http.py:306:23: invalid syntax
                  file=sys.stderr)
                      ^
poor/voice.py:54:31: invalid syntax
            print(message, end=" ")
                              ^
Makefile:30: recipe for target 'check' failed
make: *** [check] Error 1
```

The problem is that it uses Python 2 I guess. When changing the command to `pyflakes3` it works.

**Comment by rinigus** [comment]
Its python3. So, you would have to use pyflakes for python3, depending on your platform. I think on Debian you may need to specify version 3 somehow.

**Comment by rinigus** [comment]
PS: On Gentoo - where I develop - its pyflakes for python3 on my system. So, I'd better keep it as it is.

**Comment by jonnius** [comment]
Does it work for you with `python3 -m pyflakes geocoders guides poor routers` or `pyflakes3 geocoders guides poor routers`? Both do work on Ubuntu.

**Comment by jonnius** [comment]
Same question for `jsonlint`: Does `find . -type f -name "*.json" -exec jsonlint-php -q {} \` work on Gentoo? That would solve the next issue on Ubuntu.

Next I get:
```
find . -type f -name "*.json" -exec jsonlint-php -q {} \;
./packaging/flatpak/io.github.rinigus.PureMaps.json: Parse error on line 13:
...t.server1",        /* monitor availibil
---------------------^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - It appears you have an extra trailing comma
```
Maybe the jsonlint version differs between our distros. Mine is `1.7.1`.

**Comment by jonnius** [comment]
Same question for `jsonlint`: Does `find . -type f -name "*.json" -exec jsonlint-php -q {} \` work on Gentoo? That would solve the next issue on Ubuntu.

Next I get:
```
find . -type f -name "*.json" -exec jsonlint-php -q {} \;
./packaging/flatpak/io.github.rinigus.PureMaps.json: Parse error on line 13:
...t.server1",        /* monitor availibil
---------------------^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - It appears you have an extra trailing comma
```
Maybe the jsonlint version differs between our distros. Mine is `1.7.1`.

**Comment by rinigus** [comment]
pyflakes can be called via loading the module, as you suggested (as in c89fc7d57eeabbb04edf47e71882a4cd986145af).  jsonlint comes from dev-python/demjson (http://deron.meranda.us/python/demjson/), if I am not mistaken

**Comment by rinigus** [comment]
BTW, you don't need to run `check` target for make. `make install` should do... although, right now, it doesn't install executable and it is assumed that you will run it via `qmlrunner` or `qmlscene`. I will probably change it in few days, to support other distributions better.

**Comment by rinigus** [comment]
Sorry for wrong info. `make install` does install executable `pure-maps` which is the script that uses `qmlrunner`. This was implemented in the latest versions.

**Comment by jonnius** [comment]
Thanks for fixing the pyflakes issue. I don't know how to fix the jsonlint command not found, but I don't really need it, as you pointed out...
