### ISSUE TITLE
[ubports] apparmor permissions to register dbus service are missing

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#299]
see error logs: pure maps cannot register its service.

 in addition, we need permissions 

* to send dbus command to puremaps service (see exe script),

* get list of available services

**Comment by jonnius** [comment]
I quote Rodney: 
> for security, apps can't register services on the bus
> if you need to run custom services on session bus, you'll need to start a private bus for running those services, and your app can talk to those services on that bus

**Comment by rinigus** [comment]
Closing as it is impossible for UBPorts
