### ISSUE TITLE
[ubports] sms sharing

### ISSUE THREAD

**Issue by mateosalta** [rinigus/pure-maps#302]
ubports uses "message" instead of sms or text in the url to share via the messaging app

**Comment by rinigus** [comment]
I am using Sailfish specific solution right now. Please specify how can I send SMS on UBPorts. Is it some specific URI that I open with `Qt.openUrlExternally`?

**Comment by mateosalta** [comment]
yes, it works just like mailto: and would be a url - so I think would be with open url externally
format like
 "message:///5555559876?text=text%20message")
the number can be left blank too

**Comment by rinigus** [comment]
I am using now format `message:///?text=this is my text`. its implemented in 2c30d21e2744f429932ea2791057504979fd423e, available in master. please close if it works

**Comment by mateosalta** [comment]
perfect :)
![screenshot20190821_102935120](https://user-images.githubusercontent.com/1965279/63445856-c1ad9980-c3fe-11e9-92aa-41965db78dab.png)
