### ISSUE TITLE
[ubports] Text overlapping

### ISSUE THREAD

**Issue by HendriXXX** [rinigus/pure-maps#304]
In ubuntu touch we seem to have some text overlapping issue in top bar when showing route and navigating.
Tested with Nexus4 and Nexus5. Both in devel channel.

![screenshot20190821_112635295](https://user-images.githubusercontent.com/30898849/63416323-e5291200-c407-11e9-9996-a6c346f31358.png)
![screenshot20190821_073110686](https://user-images.githubusercontent.com/30898849/63416324-e5291200-c407-11e9-8a4e-1e6bafb0104f.png)
![screenshot20190821_072718878](https://user-images.githubusercontent.com/30898849/63416597-5f599680-c408-11e9-975b-694e167089ed.png)

**Comment by rinigus** [comment]
Thanks for reporting!

**Comment by rinigus** [comment]
Fixed via 565989089d66cf92da2f81c5c2df7ddfcfd7f4ea and reported as Suru issue at https://github.com/ubports/qqc2-suru-style/issues/32
