### ISSUE TITLE
Clickable fails to build

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#314]
@jonnius :

When running

```
~/code/thirdparty/clickable/clickable-dev build-libs picotts -c packaging/ubports/clickable.json  --arch amd64
```

(your clickable repo, commit d72175ce283abac53190b53cb1920d5e3137557b), I get failures when building picotts or mimic. 

Failure is `cp: target 'build_ubports/x86_64-linux-gnu/picotts' is not a directory`

Looks like when it executes build command, its already in build dir. If I make the first build command as `cp -r $SRC_DIR/* .`, build fails with `configure: error: expected an absolute directory name for --exec_prefix: build_ubports/x86_64-linux-gnu/picotts/install`

Which version of clickable did you use?

**Comment by jonnius** [comment]
It looks to me like you don't have the latest clickable version. Please get the recent master branch and try again.

**Comment by jonnius** [comment]
I just tried to checkout `d72175ce283abac53190b53cb1920d5e3137557b` but I get `fatal: reference is not a tree: d72175ce283abac53190b53cb1920d5e3137557b`. I forced pushed over it already I guess...

**Comment by rinigus** [comment]
Indeed, install of the latest clickable seems to solve the issue. Thanks!
