### ISSUE TITLE
Missing OpenStreetMap attibution

### ISSUE THREAD

**Issue by Aury88** [rinigus/pure-maps#323]
Hi, 
through Mapbox you are displaying/using also OpenStreetMap (OSM) map data 
From mapbox website you can read: "_Data: Open data is a core part of our platform. Large sources include OpenStreetMap, USGS, Landsat, Natural Earth, and OpenAddresses._" (https://www.mapbox.com/about/open/)
OSM data are under a copyright licence https://www.openstreetmap.org/copyright/en
and OSM guidelines says this:
"_Our requested attribution is "**© OpenStreetMap contributors**".
You must make it clear that the data is available under the Open Database Licence. This can be achieved by making the text “© OpenStreetMap contributors” a link which links to www.openstreetmap.org/copyright.Because OpenStreetMap is its contributors, you may omit the word "contributors" **if space is limited** (leaving it just as **© OpenStreetMap**).
You should qualify the credit to explain what OSM content you are using. For example, if you have rendered OSM data to your own design, you may wish to use "Map data © OpenStreetMap contributors"_."

and

_"For a browsable map (e.g. embedded in a web page or mobile phone application), the credit should typically appear in the corner of the map "_

but also

"_Modern mobile devices with a horizontal screen resolution of more than 480 device-independent pixels must provide attribution at least as prominent as required on a webpage. If the attribution cannot be used as a link to the licence information you must provide this information on an easily located page in the application. Devices with a horizontal screen resolution of less than 480 device-independent pixels may have attribution after “one click” -- such as an icon or link that opens a pop-up or new webpage. See below for guidance specific to wearable devices and mobile games_."

Sorry but I don't find/see the attribution over the map...is it somewhere else?

**Comment by rinigus** [comment]
Hi,

yes, the attributions are all there for all provided services. Please click to (C) or "mapbox" logo and you will be presented with the list of attributions. In case of Pure Maps, attributions depend on what provider is shown as a main map, which search results do you have, route, and bookmarks. Each subsection is shown separately. In case of OpenStreetMaps, its frequently attributed at each of the  sections. 

See example below showing application after user clicked on the logo. On Sailfish and UBPorts, separate page opens after that single click. Each of the attributions are clickable leading to the corresponding web pages. 

Let me know what you think about such implementation.

![attr](https://user-images.githubusercontent.com/15706605/64067474-c4e02b00-cc31-11e9-8507-aa10aa274b3e.png)

**Comment by sfbg** [comment]
As an OSM contributor, I'd be happy to see the attribution more prominent (and as mandated by the OSMF - text  with link in the corner.

Many people take these maps for granted and never learn, that they are completely made by volunteers.

For a great OSS product such as PureMaps, it would be good ti promote fellow open maps on which it is based as much as possible.

**Comment by rinigus** [comment]
@sfbg: many of us are contributors to OSM, myself and users of Pure Maps as well as OSM Scout Server. When adding attributions, we have to be careful and not discriminate any and also comply with the licenses. I was sure that the current implementation is compatible with the requirements and goes further by clearly showing all the data sources of the map application by layers.

Current attribution is similar (or maybe even modeled earlier in WhoGo Maps) to Mapbox GL Android and iOS implementations, as shown in https://docs.mapbox.com/help/how-mapbox-works/attribution/ (specifically https://docs.mapbox.com/help/img/attribution/android-attribution.gif). For all providers, except Mapbox, we have (C) symbol that users cannot remove in settings. This is replaced by Mapbox logo according to their conditions. Now I realize that we are missing (i) which Mapbox has in their implementation and maybe this is causing confusion. We should probably add that for clarity.

Note that Pure Maps also uses other data sources, as users can choose HERE maps. It is possible that there is no OSM data shown / used at some particular case. So, we will have to keep that in mind as well and, if any changes are needed, make it in program. Nothing super complicated, but we cannot just paste new message on the bottom either.

I looked through few apps on Android device and how OSM is attributed. Mapbox demo had the same as on the linked page. OsmAnd curiously avoided any visible attribution on the map. Looks like there was some issue filed on it and they added something on splash screen which I don't see on my device. 

So, taking all this into account - I'd like to see a link to the document cited by @Aury88 regarding mobile application which had some specific instructions depending on pixel size of the device. I hope that this will bring clarity and show which direction we should go for. Any legal expert advice from OSM side is welcome as well. Pure Maps and OSM Scout Server do rely on OSM strongly, I just don't want to make anyone "more equal" than others in such modular and extensible application as Pure Maps.

**Comment by rinigus** [comment]
PS: Please let's take it all very seriously and find the solution that is clearly complying with all the data licenses, if the current implementation does not satisfy it.

**Comment by Aury88** [comment]
> Hi,
> 
> yes, the attributions are all there for all provided services. Please click to (C) or "mapbox" logo and you will be presented with the list of attributions. In case of Pure Maps, attributions depend on what provider is shown as a main map, which search results do you have, route, and bookmarks. Each subsection is shown separately. In case of OpenStreetMaps, its frequently attributed at each of the sections.
> 
> See example below showing application after user clicked on the logo. On Sailfish and UBPorts, separate page opens after that single click. Each of the attributions are clickable leading to the corresponding web pages.
> 
> Let me know what you think about such implementation.
> 
> ![attr](https://user-images.githubusercontent.com/15706605/64067474-c4e02b00-cc31-11e9-8507-aa10aa274b3e.png)
Thank you ! Yes, this implementation seems to me comply the OSM copyright and the guidelines. Probably the missing (i) would have helped me understand that it was not a static not-clickable watermark and so it would help me find the attribution, but I think it is not a "must have"
Thank you again.  
ps: the document you ask about  is an "official" draft to better explain the copyright application but imho the 480 pixel-thing applies if OSM is the only source (and so in that horizontal space there is enough space for the OSM attribution) and this is clearly not the case having more than one source.
https://docs.google.com/document/d/1e_IQYHtqVivGRw4O4EOn6__-LGMuzPlWz6XKEdAkwW0/edit

**Comment by rinigus** [comment]
Thanks! I have adjusted the attribution button - it should be clearer now. Will be a part of the next release
