### ISSUE TITLE
Provide DBus API for navigation state

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#327]
Provide current state of navigation via DBus. Would be useful for hooking other applications into it, in particular, smartwatches.

From http://talk.maemo.org/showpost.php?p=1560017&postcount=865

**Comment by rinigus** [comment]
While we can design API (or more specifically what is broadcasted and can be called as a method), it will probably come after #247

**Comment by StefWe** [comment]
It is a bit hacky, but as a first try pure map can generat a  notification. The smartwatch shows every notification 😁

But a dbus api is a much better and more universal solution.

**Comment by rinigus** [comment]
In case of Pure Maps, it will be easier to make DBus API than use notifications. Would probably work on navigation in september, from the beginning of it

**Comment by rinigus** [comment]
Docs are missing
