### ISSUE TITLE
Spin off cross-platform QML modules

### ISSUE THREAD

**Issue by nodevel** [rinigus/pure-maps#330]
As far as I know, the code developed for cross-platform support (Silica, Kirigami, UBPorts, pure QtQuick Controls) is by far the most complete code base for supporting all these platforms at once (there has been a similar effort in Modrana, but it is not as actively developed).

With the emerging Linux phones, such as PinePhone or Librem 5, it will be more and more important to unify the efforts to have single code base for all these platforms, not just for Pure Maps, but other currently Silica/Kirigami/UBPorts-only apps.

Would it make sense to spin these components off to a separate repository where it could be used as a submodule in Pure Maps and in other projects?

**Comment by rinigus** [comment]
Its an idea I have been toying with as well. In some aspects, it has the application-dependent parts. However, its probably possible to get rid of those and partition into generic platform abstraction and application-specific part. 

What was keeping me back is relatively simple - I am not sure developers will use it in practice. Same as universal components developed for modRana. While I do use the same components for Pure Maps and OSM Scout Server, they don't cover all functionality offered by different platforms as I didn't need it. So, before investing time into formulating the developed components, I think we should see who is interested. And not in an abstract way, but is ready to convert the apps into it. If such interest is there, we can start making the components into separate project and document it while new users are starting to use them.

Now where should we make the call for QML developers? All are scattered at different forums according to the platforms they use.

**Comment by nodevel** [comment]
That is a good question. Let me explain what lead me to raising this suggestion.

I would like to see some of the apps I have been using on SailfishOS become multiplatform (be it for a use on the desktop or on postmarketOS) and I would like to personally contribute to make this happen (by implementing the cross-platform code in these apps). The problem is that I do not have enough time to fork these apps and maintain the fork (plus it would be an unnecessary split of forces if these apps are actually actively developed). That's why I'd approach their developers and ask if they'd mind if I contributed the cross-platform code. The problem with this approach is that if I tell them "let me expand the code base three-fold; back to you", it's only logical that this would be a burden to their development, having to maintain this code (let's say a fork of your multiplatform code). Therefore the first logical step before contacting them seemed to raise the question of having this as a submodule, as it may lead to better reception on developer's side.

I was personally thinking of opening a PR for a few apps that (outside of QML) do not have any platform-specific code, such as Kaktus, Talefish, SailWave, ZuTun.txt and similar. To be honest I haven't checked what functionality is missing in your platform abstraction code yet.

It will likely be easier to make a broader call for adoption once there are some success stories.

**Comment by rinigus** [comment]
I would be interested in making this cross-platform as a separate project/submodule or similar if there are more developers behind it. It will also allow us to share the load on keeping it multiplatform.

Right now, the multiplatform code sits as a subfolder in qml allowing me to add some app-specific bits into it. For example, handling of the cover page in SFOS, split of multipage arrangement in Kirigami (keeping map on the left and search pages overlapping each other on the right). Essentially, we will have to find a form where we get most of the platform-dependent code into these separate wrapper components and, at the same time, allow to make some platform-specific app adjustments. Maybe some apps will not need such platform-specific bits, but there should be a way to specify that as well.

**Comment by rinigus** [comment]
Let's make it a touch more specific - which app would you prefer to start with?

**Comment by delijati** [comment]
This _ui-toolkit_ should have for every _target-platform_ a Dockerfile to make it easy to play, build with on Desktop e.g.:
```
$ docker build -t ubports Dockerfile.ubports
$ docker build -t silica Dockerfile.silica
...
$ docker ... ubports bash -c "cd /app/dev && qmlscene qml/pure-maps.qml"
...
# example Dockerfile running on nvidia -> https://github.com/delijati/fosdem-qml#run 
```
This will probably not work for interactions with some phone specific service e.g. `DownloadManager` but a dev should at least see if a app starts on all platforms without knowing platform specific details.

**Comment by delijati** [comment]
Docker build chain for sailfish: https://together.jolla.com/question/188328/howto-compile-applications-with-docker-instead-of-virtualbox/

**Comment by rinigus** [comment]
As far as I know, we can compile using docker, but not run via it on Sailfish. So, it wouldn't work for testing anyway. As it is, developers can test on desktop PCs (Kirigami and QC platforms), docker (UPBorts) and using device/virtual env for SFOS.

**Comment by rinigus** [comment]
@dylanvanassche has started a spin-off project at 

https://gitlab.com/dylanvanassche/convergence-components

Closing here.
