### ISSUE TITLE
(ubports) nav arrow on wrong side while in landscape

### ISSUE THREAD

**Issue by dieharddan** [rinigus/pure-maps#331]
While switching to landscape, the arrow moves to the wrong side of the screen and nav texts disappear. this is using a oneplus one device

![screenshot20190909_140318776](https://user-images.githubusercontent.com/51171015/64621754-c51cbb00-d3d5-11e9-8458-7c278de13721.png)

**Comment by rinigus** [comment]
That's bad. Is it for some time or stays there? I cannot reproduce the error, but I do see some binding loops reported

**Comment by dieharddan** [comment]
i believe it worked correctly very briefly at first, but then started doing this. I will try to set the settings back to default to see if that is what triggers it

**Comment by rinigus** [comment]
Noh, it could be something unfortunate which triggers, what seems to be, a bug on Pure Maps side. Let me see how to fix it.

**Comment by rinigus** [comment]
it was induced by the wrong anchor of the arrow. Became visible on UT since it had rather large navigation icon (fixed already). Should be fine in the next release

**Comment by dieharddan** [comment]
Excellent! thanks
