### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by vokaliz** [rinigus/pure-maps#339]
Hello! Sorry, but today I used Pure maps on Maizu pro 5 (ubports OTA-10) in horizontal orientation, look attachment please. 
![screenshot20190914_084707315](https://user-images.githubusercontent.com/39481201/64911629-1b1e9500-d72d-11e9-9859-b9ebd34ecff8.png)
ETA (Прибытие) and time must have more big font. Arrow must be in the left top corner. Before release update in OpenStore  fix this problem, please!

Best regards, Dema!

**Comment by rinigus** [comment]
There is a release 1.25.0 already in OpenStore with issues in search, but arrow and translation should be OK. The font is selected that way deliberately and will stay so. At least until I move all navigation elements around and will be able to discuss sizes with the new design.

New release 1.25.2 is prepared, you may want to wait for that.

If your screenshot is from 1.25.0, please let me know.

**Comment by vokaliz** [comment]
Ok! Big thanks!

**Comment by rinigus** [comment]
Closing the issue as it is expected to be fixed

**Comment by vokaliz** [comment]
Version 1.25.2 looking very good! Today morning I tested. Thank you!
