### ISSUE TITLE
TTS invocation provides no initial audible feedback

### ISSUE THREAD

**Issue by Olf0** [rinigus/pure-maps#34]
Originally reported as [Poor Maps' issue 69](https://github.com/otsaloma/poor-maps/issues/69).  When rereading this, after just having carried out a test with Pure Maps 1.3.0 (see below), I have the impression that the overall behavior of the voice navigation has become much more reproducible (or I just got used to carry out this test reproducibly), although the fundamental issue still persists.

I just walked around the block, following a precalculated route.

Side notes:
- Pure Maps was started before a GPS fix was obtained.  After a GPS fix was acquired, it took Pure Maps more than two minutes to visibly react to position updates.
- At the start I had misconfigured the routing provider in OSM Scout Server.  Thus when I started hitting "↻Reroute", the message "Rereouting failed" was displayed on the screen.  After hitting "↻Reroute" a few more times, the message "Rereouting failed" was also narrated via TTS, and from that point on the "Rereouting failed" message was **always** successfully "spoken".
- Hence I did let Pure Maps calculate a new route with OSM Scout Server as routing provider: Pure Maps was displaying a big, circling **↻** for more than two minutes, but when I interrupted the location search and route calculation, a properly calculated route was displayed and usable (or I coincidentally returned to the map view in the moment, the route calculation was finished).

The fundamental behavior was still the same, though:
1. About every third time hitting "↻Reroute", the message "New route found" was also "spoken" (it is always displayed).
2. About every third time "↻Reroute" is spoken, the first navigation instruction is also narrated (it is always displayed).
3. If the first navigation instruction is successfully narrated, Pure Maps' voice navigation works fine for the whole route (until hitting "↻Reroute", again).

Tested with Pure Maps 1.3.0 (and WhoGo Maps / Poor Maps before) under SFOS 2.1.4.14 on a Jolla 1 phone.  TTS engine used is picotts.
BTW, I switched off the 3D view (while navigating), as it is too slow to be fun for practical use on a Jolla 1 (but working fine!).

**Comment by Olf0** [comment]
P.S.: The output of Pure / WhoGo / Poor Maps WRT this issue, when started at the command line has not revealed much in the past, beyond `pico2wav` was called, when TTS works, and not, if not.
Furthermore this issue has also been reported by users of Mimic on TMO.

If you have any suggestions for more comprehensive logs or if you think it makes sense to capture the output of a recent Pure Maps, when started at the command line, please let me know.

**Comment by Pohli** [comment]
I also had the impression that sometimes TTS didn't work in WhoGo Maps and in earlier versions of Pure Maps. But in the last few updates of Pure Maps the issue hasn't occured again. I mostly use Stadia Maps as router, sometimes OSM Scout, too.
The only thing I've noticed in every version so far is that directly after starting a freshly calculated route there's no TTS for the "initial" directive, same after rerouting. Only the next directive is spoken which can last long time when starting navigation while driving on a long road going straight, no turns or roundabouts. Maybe that's what makes my impression I mentioned above.

Pure Maps 1.7.0 (PicoTTS) on Jolla1 Phone

**Comment by Olf0** [comment]
Triggered by @Pohli's comment, I retested this with PureMaps 1.9.0 using PicoTTS 17.08.10, OsmScout as routing library provided by OsmScoutServer 1.12.2 on a Jolla 1 under SFOS 2.2.1.18 (the original report here was for PureMaps 1.3.0, while @Pohli tested with v1.7.0):
Yes, TTS navigation has become even more stable compared to early releases of PureMaps (and much, much better and reproducible compared to PoorMaps and WhogoMaps)!

I fully support his observation, that currently the only reproducible flaw left is:
> The only thing I've noticed in every version so far is that directly after starting a freshly calculated route there's no TTS for the "initial" directive, same after rerouting.

But this happens in only ca. 50% of my tries with PureMaps 1.9.0, about half of the tries it works immediately.
And as before: When PureMaps once started "talking", it always continues to work fine until exiting the navigation mode.

P.S.:
@rinigus, I asked myself, if PicoTTS could be easily updated to a newer version (even though I do not expect that to cure this issue), only to find out, that it originates from Google's [AOSP tree](https://android.googlesource.com/platform/external/svox/+/master) ([as you mention](https://openrepos.net/content/rinigus/picotts)).
Maybe the effort by @gmorenz, [providing scripts for fetching and compiling PicoTTS under a regular Linux distribution](https://github.com/gmorenz/pico-tts) is helpful for you (as I assume you basically did the same, but manually).  As PicoTTS seems to have been declared EOL by Google (so maintenance has more or less stopped), it may make sense to create a presumably "final" release for SFOS from it.

From my experience, PicoTTS is by far the best working TTS for SFOS:
- Mimic is "English only", really resource hungry and I never had it working in Pure/WhoGo/PoorMaps (but at the command line with garbled output).
- I never found a Flite compiled for SFOS, although it is [mentioned as a TTS engine](https://openrepos.net/content/rinigus/pure-maps).
- I also haven't found a eSpeak compiled for SFOS (although it is also [mentioned as a TTS engine](https://openrepos.net/content/rinigus/pure-maps)), but having tried eSpeak as an Android TTS provider under AlienDalvik, I can can tell that eSpeak sounds funny, but the TTS quality is simply unbearable, rendering it unusable!

**Comment by rinigus** [comment]
Re TTS engines:

PicoTTS is in this sense "final" compilation. There is no further development going on with it and I think I did use the "final" version.

Mimic and Flite are the same, except Mimic has AP voice. Try to use female voice model, that I would expect to have smaller footprint.

eSpeak is, indeed, just disturbing more than helping.

Would have to make new research on TTS engines at some time and see new developments in the area.

**Comment by Olf0** [comment]
Thank you for the information.

- I did a *little* search on the web today and unfortunately there does not seem to be any new developments WRT Free Software TTS engines.
- PicoTTS is working fine (at least for me and except aforementioned issue): TTS quality and resource usage is good, plus it provides multiple languages.  Although its quality is not really up to today's standards.  Knowing it is in its "final" state, that's at least one thing less to think and care about. ;)
- While I considered trying Mimic again on an Xperia X, the facts that nobody described its output as exceptional and that it is "English only", make this "low priority (probably never get around to do that)" for me.
- What is an "AP model" in the context of speech synthesis?

**Comment by rinigus** [comment]
AP model -> sorry, AP voice of mimic. Its actually quite good. As for developments, [Mimic 2](https://mycroft.ai/blog/mimic-2-is-live/) may be of interest, but let's see if we get it ported.

**Comment by Olf0** [comment]
Ah, missed that two days ago:
https://mycroft.ai/blog/mimic-2-is-live/
https://github.com/MycroftAI/mimic2
Thanks for the hint to look for "Mimic 2", that's really interesting to read.
Although it makes me a bit afraid of the resource use Mimic 2 may have.

**Comment by Olf0** [comment]
Oh, I missed to mention the PicoTTS-fork [nanoTTS](https://github.com/gmn/nanotts) for long.
Though nanoTTS focuses on improving *pico2wav* (i.e., its API, but not the TTS engine), it may be helpful.

**Comment by Olf0** [comment]
Oh, [you are already using nanoTTS](https://github.com/rinigus/pkg-picotts/blob/master/README.md) (and may have implemented it).
Sorry for the unnecessary post (I should have looked more closely in the first place).

**Comment by rinigus** [comment]
I wonder if we still have this instability and whether ability to test TTS engines already addressed main concerns with this.

**Comment by Olf0** [comment]
I have not used this much lately, but it was working fine on my Jolla 1, when I did.
I also have not read any comments from others (e.g., at TMO) WRT this, anymore.

So, yes, closing seems to be the right thing.

**Comment by Olf0** [comment]
Retested in real life situations last week.  Unfortunately I have the impression that PureMaps' behaviour is still exactly the same as in @Pohli's [description](https://github.com/rinigus/pure-maps/issues/34#issuecomment-430707588) for PureMaps 1.7.0:
> The only thing I've noticed in every version so far is that directly after starting a freshly calculated route there's no TTS for the "initial" directive, same after rerouting.

IMO it would be very helpful to emit via TTS "Voice navigation started" (or simply use the on-screen message text "Navigation on") rsp. "Rerouting finished" to ensure the user that no navigation instruction is missed.
Currently when the navigation mode with TTS is started, PureMaps stays silent, while there should be some audible feedback to make clear everything is working fine, because each time there are so many potential reasons for failing, e.g. low audio volume, failed BT connection etc.  Better to provide users with the ability to realise that right at the start of an navigation, then later (while navigating).

P.S.: In the past I was able to hear a "Rerouting completed" (or "Rerouting finished"?) every now and then, but outputting this via TTS never was stable on my Jolla 1 phones.  Now that always seem to fail, no matter how often I manually trigger a new route calculation while navigating with TTS on.

**Comment by rinigus** [comment]
Good ideas! I'll look into it

**Comment by rinigus** [comment]
I have worked on TTS a bit and made a set of standard messages (starting, rerouting, ...) which should play on corresponding action (unless a newer message comes meanwhile). Please reopen if it doesn't work in the next release

**Comment by Olf0** [comment]
Thanks a lot & will do, if necessary.
