### ISSUE TITLE
compass not working [xa2, sf3.1]

### ISSUE THREAD

**Issue by sbridger** [rinigus/pure-maps#340]
I assume the little compass symbol is supposed to do something. (it just points north all the time)

It is working in "orienteeringcompass" app

(I don't think it is really getting gps either, but havn't explored this properly yet)

**Comment by rinigus** [comment]
it shows orientation of the map while navigating. Assuming that you allow map to rotate according to your movement.

**Comment by sbridger** [comment]
OK, looks like it only uses the GPS direction, not the magnetic compass. GPS direction seems to be only updating  when I walk ~10m (and when GPS is working). Note that GPS wasn't actually updating until I enable accurate positioning using mozilla. (showing 0 satellites in GPOSInfo app)

So this will turn into a feature request for magnetic compass when stationary

**Comment by rinigus** [comment]
that issue has been filed already :)

**Comment by sbridger** [comment]
Is it https://github.com/rinigus/pure-maps/issues/260
