### ISSUE TITLE
Thank you for last ubports realease

### ISSUE THREAD

**Issue by vokaliz** [rinigus/pure-maps#341]
Hello! Firs of all my big thanks for the 1.25.2 realease, now Pure Maps looking very good (look attachment). 
![screenshot20190915_065628726](https://user-images.githubusercontent.com/39481201/64917074-8059a100-d794-11e9-85a4-bc5b357c6ad1.png)
![screenshot20190915_065746684](https://user-images.githubusercontent.com/39481201/64917075-8059a100-d794-11e9-958e-0d3311b8edb8.png)
For future enhensement of the PM, could you use Yandex Navigator target search algorithms? Some points current algorithms cannot find even in Moscow. It's not critical, but it takes a long time to set the right direction.
I like the app, it has a good future. Thank you!

**Comment by rinigus** [comment]
Thank you! Please open a separate issue for Yandex. As such, these types of messages should be done via forum..
