### ISSUE TITLE
Text field looses focus after clear button pressed

### ISSUE THREAD

**Issue by Pohli** [rinigus/pure-maps#345]
Editing text fields of a bookmark: after tapping clear button I have to tap the text field to enter edit mode again. IMO it should stay in edit mode after tapping clear button.

**Comment by rinigus** [comment]
Agreed. Looks to be an issue in Silica. In other platforms its working as it should. Just plain setting of the focus (or active focus) after clearing text seem to fail, unfortunately. Will have to dig deeper...

**Comment by rinigus** [comment]
Fixed in 6b277ab8a56d916dc4c427c712616e947e3c9b40

**Comment by Pohli** [comment]
Yes, just tested and it's working correctly now. Thanks for fixing!

**Comment by rinigus** [comment]
You're welcome!
