### ISSUE TITLE
Sharing: Add actual address

### ISSUE THREAD

**Issue by sbridger** [rinigus/pure-maps#354]
Just wanted to do this today: text the street address (on the (i)page), not the coordinates.

**Comment by rinigus** [comment]
That would depend on whether you are sharing current location or POI. For POI, it should be simple to implement as it has address as one of the properties. For current location, the reverse geocoding is needed which I think is too much for sharing code.

**Comment by sbridger** [comment]
The (i) page is already showing the information I want (street name) about the selected point, that's not an issue. 

The issue is that 
a) the text can't be selected and just copied to clipboard off the (i) page
b) the sharing page only offers coordinates, not the street address

**Comment by rinigus** [comment]
OK, then its not too difficult. We will have to forward to the sharing page not just coordinates but full bunch of information and then offer to share that info in addition to coordinates

**Comment by rinigus** [comment]
Functionality added, will be a part of the next release

**Comment by sbridger** [comment]
Another variant I have wanted to do (quite often), is to share the predicted ETA by sms.
i.e. send an sms like "ETA 12:55pm at 5 Long Rd"

**Comment by rinigus** [comment]
add new issue :)
