### ISSUE TITLE
Nearby Venues regression 

### ISSUE THREAD

**Issue by accumulator** [rinigus/pure-maps#36]
When using the Nearby Venues search option in both WhoGo Maps and Pure Maps, I get no results when using Pure Maps, while I do get results using the same query in WhoGo Maps.

Using downloaded map of the Netherlands;

- Using: MapQuest Nominatim
- Near: Rotterdam
- Type: Drinkwater
- Radius: 5 km

WhoGo Maps: 11 results
Pure Maps: no results

**Comment by rinigus** [comment]
Someone used my keys for MapQuest and managed to wipe out all quota for a month. See https://talk.maemo.org/showpost.php?p=1547576&postcount=22

Until the counter is reset, either use other nearby search or WhoGo Maps. Not much I can do on the client side. New keys are generated and we have just to wait

**Comment by accumulator** [comment]
Oww that's awful :(

Is it possible to to show an error if the results from the backend are not retrievable? Now it just looks like there are no results..

**Comment by rinigus** [comment]
Related: https://github.com/rinigus/pure-maps/issues/33
