### ISSUE TITLE
Voice navigation volume is very low

### ISSUE THREAD

**Issue by ruedigerkupper** [rinigus/pure-maps#361]
When using voice navigation, volume is so low that it can't be heared in a moving car. Volume is already set to maximum (using volume rockers or system indicator). Is there a speacial in-app volume? If so, I could not discover a way of changing it.

**Comment by ruedigerkupper** [comment]
This is Ubuntu Touch on a Nexus 5.

**Comment by rinigus** [comment]
see last note on https://open-store.io/app/pure-maps.jonnius . please close the issue if it resolves it

**Comment by rinigus** [comment]
Did it help?

**Comment by ruedigerkupper** [comment]
Will try tonight, thanks!


-- 
Dr. Rüdiger Kupper
Forststr. 3
72250 Freudenstadt

**Comment by ruedigerkupper** [comment]
Yep, that helped (sorry, I should have read the description).
However, the voice sounds distorted (volume slider is set to max, but no amplification).

**Comment by rinigus** [comment]
I think its out of Pure Maps reach and should be dealt with on ubuntu touch level. As such, the instructions are produced as TTS and voiced. Voice amplification/volume is probably OS business, not of application. I would suggest to ask for help in UT forums/rooms.

Closing it here. Feel free to reopen if you believe/find evidence that its Pure Maps specific issue

**Comment by ruedigerkupper** [comment]
No, you're probably right. What system does Pure Maps use for TTS?
Thanks for your help!

**Comment by rinigus** [comment]
for English, its using Mimic; for German and few others - picoTTS
