### ISSUE TITLE
Issues with text-to-speech in the German language

### ISSUE THREAD

**Issue by ruedigerkupper** [rinigus/pure-maps#362]
I noted two minor issues in German TTS output:

1) The display shows distance in English notation (with a dot, e.g. "2.3 km"). In German notation, a comma would be used ("2,3 km"). Germans have adopted to this (very common) confusion in reading. But it is very irritating in TTS: The phrase produced is "zwei Punkt drei Kilometer" but it should be "zwei Komma drei Kilometer".
The best way of fixing this is probably changing the screen display to German notation in the first place. Then TTS would produce the correct phrase.

2) When a sentence ends in a road number (like in "… dann abbiegen auf 79." – "… then turn onto 79."), the number is phrased like an ordinal number: "… dann abbiegen auf siebundneunzigste." – "… then turn onto seventy-ninth." Obviously the TTS system reads the full stop at the end of the sentence as an ordinal point, which it isn't.

**Comment by rinigus** [comment]
Let me check it. As we have only online service available for Ubuntu, there is not enough control over it.

**Comment by rinigus** [comment]
Distance is formatted in Python code (under utils.py) and it doesn't take into account requested locale. Opened #363 to tackle it

Point 2: cannot help with it. Is this a correct way to write it in German? If it is, please check if some more clever TTS engines know how to pronounce it correctly. After that research, it will be possible to decide whether to file the issue against Valhalla

**Comment by ruedigerkupper** [comment]
Point 1: Thanks for creating the issue.
Point 2: The issue is not specific to German, I'd expect that it appears in English as well. The easiest way of fixing it is obviously removing the full-stop at the end of the string passed to TTS.

**Comment by rinigus** [comment]
I am not sure I understand. I don't think I get any full stops in English. Can you make an example in English and explain what's wrong in TTS, so I can test it myself?

**Comment by ruedigerkupper** [comment]
Sure. I've been using Pure Maps for navigation recently. When turning onto a numbered road, the TTS produced the German equivalent of "turn onto third" instead of "turn onto three" (referring to the road number).
I concluded that the string passed to TTS was "turn onto 3." and the "3." was read as an ordinal number. Please check if the strings passed to TTS have a full-stop (".") at the end. If so, the easiest way of fixing the problem is removing this character.

Test strings:
English: "turn into 13." vs. "turn onto 13"
German: "abbiegen auf 13." vs. "abbiegen auf 13"

**Comment by rinigus** [comment]
Thanks! Will test and look where the full stop is coming from

**Comment by rinigus** [comment]
Fixed (finally!) locale number formatting, will be part of the next release. As for the fullstop part of the issue, it looks to be coming from the router (Valhalla). I am reluctant to start processing incoming strings. If it is an issue with TTS pronouncing those sentences, would be better to fix in Valhalla.

At least some online providers do not format the numbers according to requested locale. When testing against Valhalla as in OSM Scout Server, the numbers inside verbal sentences appear to be correct (checked with German).

Closing it here. Please feel free to discuss even if closed and, if needed, reopen the issue.

**Comment by ruedigerkupper** [comment]
Thanks for fixing the locale formatting!
