### ISSUE TITLE
[feature request] Add thunderforest outdoors vector tileset

### ISSUE THREAD

**Issue by mdehollander** [rinigus/pure-maps#364]
There is a new version of the beautiful Thunderforest Outdoors Vector tileset: https://www.thunderforest.com/blog/vector-outdoors-v2/

Would it be possible to add Thunderforest vector tiles to Pure-maps? They are available in Mapbox Vector Tiles format. 

I looked at https://github.com/rinigus/pure-maps/tree/master/maps for examples of vector tileset specifications, but I don't see yet how to convert the mapbox specs to thunderforest outdoors.

**Comment by rinigus** [comment]
For adding these maps, we need corresponding style. I presume they will be providing them. As soon as styles are available, its easy to add maps too

**Comment by mdehollander** [comment]
Is this pointing to a style?: https://tile.thunderforest.com/thunderforest.outdoors-v2.json?apikey=9a913f34956945b494e3b9f5159968ad

Otherwise I need to ask the author.

**Comment by rinigus** [comment]
No, it doesn't look like it. drawing elements are missing, fonts are missing. Here is the style spec: https://docs.mapbox.com/mapbox-gl-js/style-spec/

**Comment by mdehollander** [comment]
@gravitystorm I would like to add the thunderforest outdoor vector tileset to pure-maps (a navigation app for sailfish and ubuntu touch). Apparently we need mapbox-gl style specification in order to render things. Do you also provide such a style?

**Comment by gravitystorm** [comment]
> Do you also provide such a style?

Not yet. For now it's just the underlying vector data tiles that are available.

**Comment by rinigus** [comment]
@gravitystorm : thanks for prompt reply! It takes considerable effort to design the tile schema, as you did, as well as design style(s) around it. For those interested in helping with the style design, it would make sense to develop it together with Thunderforest team directly. That way it will be visible to the developers of all map clients and not Pure Maps only.

**Comment by mdehollander** [comment]
Thanks Andy for your quick answer. Closing this issue here since there won't be a easy solution to add the style.
If the styles are available or there is a community effort to create them, we can continue here.
