### ISSUE TITLE
Ubports - Arm64

### ISSUE THREAD

**Issue by ernesst** [rinigus/pure-maps#365]
With the add of arm64 architecture phone to ubports - PinePhone, Oneplus 3, Xperia X, could you please compile the app for it ? 

Thanks

**Comment by rinigus** [comment]
should be possible. @jonnius - would you look into it?

**Comment by jonnius** [comment]
Latest Clickable master branch has full arm64 support, so I just crafted a click package.
[pure-maps.jonnius_1.26.1_arm64.zip](https://github.com/rinigus/pure-maps/files/3884042/pure-maps.jonnius_1.26.1_arm64.zip). Please rename to `*.click` (Github wouldn't let me upload it as a click). It is only missing high quality Mimic TTS, but has PicoTTS included. Could you please test and give feedback?

OpenStore multi arch support is still work in progress. As soon as it has arm64 support, I'll get Pure Maps up for arm64. The build configuration just needs a little tweak to set the architecture correctly in the manifest file.

**Comment by ernesst** [comment]
Thanks for the build, 
On a OP 3 under Edge, the application got stuck but after two reboots  the app shows up as normal.
I'll test a ride this week.

**Comment by ernesst** [comment]
The application runs fine on the phone, thanks
