### ISSUE TITLE
Undefined symbol in libqmapboxgl

### ISSUE THREAD

**Issue by jonnius** [rinigus/pure-maps#367]
I just wanted to make the arm64 and amd64 releases on the OpenStore and built everything fresh. Now the app crashes even on armhf with
```
qmlrunner: symbol lookup error: /opt/click.ubuntu.com/.click/users/phablet/pure-maps.jonnius/lib/arm-linux-gnueabihf/libqmapboxgl.so.1: undefined symbol: _ZN4mbgl15RenderFillLayerC1ENS_9ImmutableINS_5style9FillLayer4ImplEEE
```

The [prepare-deps.sh](https://github.com/rinigus/pure-maps/blob/master/packaging/ubports/prepare-deps.sh) simply clones the dependency repositories. Should I checkout some specific commit/git tag instead?

**Comment by rinigus** [comment]
I would expect this type of error coming from a build which has some parts mixed up. So, its strange that this came out from a fresh build. Maybe you should try again after wiping all compiled code away?

**Comment by jonnius** [comment]
I started over and gcc crashed due to an internal compiler error while compiling mapboxgl native. At second try it succeeded and the app runs now.
