### ISSUE TITLE
add support for navigation with waypoints

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#37]
Add waypoints support for routers (To, From, Via)

**Comment by Thra11** [comment]
I was thinking about this recently. Can via points be implemented entirely on the client side, simply by asking the server for each segment separately and combining the results? Or are there advantages to having the server API support via points?

**Comment by rinigus** [comment]
I think most of the routers (if not all) do support waypoints. However, on client side, I have to rewrite navigation part (#247) to be able to detect when have we reached waypoint and passed it. This is needed to ensure that rerouting will not bring you back to the waypoints that you passed already.

**Comment by Thra11** [comment]
I was assuming that it could stitch the segments together and then treat them as a single route, without any need to do anything special at the via point.

**Comment by Thra11** [comment]
(Sorry, ignore that reply. I didn't read your response carefully enough and had completely forgotten about rerouting)

**Comment by Thra11** [comment]
Presumably this is simple enough if the user passes through (within margin of error) the via point, but slightly more difficult if they go a slightly different route: it might not be possible to tell whether they still want to go to the via point or not without asking.

**Comment by rinigus** [comment]
Yeah, I am targeting fully automatic solution, as much as possible. Mainly for safety reasons.

**Comment by Talkless** [comment]
+1, "Via" waypoints are really important to optimize route manually by your local knowledge.
