### ISSUE TITLE
Generic searches

### ISSUE THREAD

**Issue by aclifton314** [rinigus/pure-maps#374]
I was playing around with Pure Maps earlier today and I really like the layout and the functionality of the app.

I didn't dig too deep, but I was wondering if it were possible to do generic searches in Pure Maps to show results near my current location or the location I am looking at on the map.

For instance, if I type in "restaurants" into the search the top 3 results are in France, Afghanistan, and the US. Is it possible to have Pure Maps show results for "restaurants" based off either my current location or the location I am currently looking at on the map?

Thanks in advance!

**Comment by rinigus** [comment]
Yes, sure. Its called "Nearby venue" and is accessible via menu, by tap-and-hold to generate point of reference and clicking on nearby venue icon. Then you have to give the distance from the point of reference (radius), type of venue (restaurant), and maybe something extra can be specified depending on provider (there are 2 providers for online and one offline provider).

For offline mode, using OSM Scout Server maps, you could also search for restaurants and such along a route. This is possible if you have route calculated and then try to search using nearby venue search.

Closing it here, please feel free to reply as I get notifications for closed issues as well. If you think it should be addressed more, reopen or open a new specific one.
