### ISSUE TITLE
[ubports] wrong standard paths

### ISSUE THREAD

**Issue by StefWe** [rinigus/pure-maps#379]
For some reason the default paths of the application are set wrong. The app name is used twice.

### Actual paths after installing
/home/phablet/.cache/pure-maps.jonnius/pure-maps.jonnius/
/home/phablet/.config/pure-maps.jonnius/pure-maps.jonnius/

### Expected paths
/home/phablet/.cache/pure-maps.jonnius/
/home/phablet/.config/pure-maps.jonnius/

Pure Maps version: 1.26.2

**Comment by rinigus** [comment]
That sounds like an issue with Ubports packaging. @jonnius ?

**Comment by jonnius** [comment]
I cannot really see any issue in the build configuration or resulting click package. Might it be related to the fact that we pass `-P pure-maps.jonnius` to qmlrunner?

**Comment by jonnius** [comment]
From app dev group I learned that it depends on whether an organization name is set or not. If we see an issue in that doubling paths, we should try to set or not to set one.

**Comment by rinigus** [comment]
I see. I guess we have organization and the app called the same way. I would classify it as minor and would suggest to live with it :)

**Comment by jonnius** [comment]
Agreed.

**Comment by rinigus** [comment]
closing as minor.
