### ISSUE TITLE
Offline mode fails "loading style failed: Connection refused"

### ISSUE THREAD

**Issue by vasyugan** [rinigus/pure-maps#389]
When switching to offline mode,  I get the message  "loading style failed: Connection refused"

Obviously Puremaps uses the OSM Scout tile server for offline tiles. Is the URL outdated?

**Comment by rinigus** [comment]
No, all urls should be the same. More info is needed: platform, was osm scout server running?

**Comment by vasyugan** [comment]
Platform: Latest Ubuntu Touch ([community port for Xperia X](https://devices.ubuntu-touch.io/device/suzu/) 
I don't know which server Puremaps uses, so I don't know how to check, sorry. I have been trying for a couple of days now, the result is always the same.

**Comment by rinigus** [comment]
No problem. On Ubuntu Touch, you have to install https://open-store.io/app/osmscout-server.jonnius for offline operation. Note that in your platform, look for specific instructions on OpenStore page as UT suspends apps in background by default.

If you get in trouble configuring the server, check out manual at https://rinigus.github.io/osmscout-server/en/ describing how it operates. While specific config is shown using Sailfish and few versions ago, UT is very similar to it.

Let me know how it went and whether you have more questions.

**Comment by rinigus** [comment]
Noted, some extra message is needed.

In theory, someone can write some other server to use for offline data. There are also help messages regarding it on Pure Maps application description in the stores (Ubuntu Touch, Sailfish, Flathub). So, its expected that users would read those...

**Comment by vasyugan** [comment]
I see. The problem is that the note that you must install the server is by default hiddden in the OpenStore on the device. It only becomes visible when you click the small down arrow.

**Comment by jonnius** [comment]
I just moved the note to the top. So should attract more attention now.

**Comment by vasyugan** [comment]
Thanks! It would be brilliant if in addition to that, the "loading style failed: Connection refused" would be appended with something like "Did you install OSM Scout Server, available from the appstore?"

**Comment by rinigus** [comment]
It's good idea, I will look into it. Keep this issue open and, when fixed, we can revert description to more logical order in OpenStore.

**Comment by rinigus** [comment]
Fixed and will be part of the next release

**Comment by vasyugan** [comment]
> Fixed and will be part of the next release

Thanks, keep up the good work!
