### ISSUE TITLE
Map is in cyrilic

### ISSUE THREAD

**Issue by adocampo** [rinigus/pure-maps#406]
I'm trying puremaps on my plasma desktop.
I noticed map labels appears in some cyrillic language
![image](https://user-images.githubusercontent.com/2266612/87282872-fc2b9380-c4f4-11ea-9b38-fe44f7a383a5.png)

I don't know why and how to change it to a romanic alphabet. My bet why appears in cyrilic is because my ISP is DIGI, which is a romanian provider, and probably its IP pool points to Romania, yet my ip address seems to be on my conutry (spain).

I searched on the settings, but I couldn't find where I can change the language, besides "Preferences --> General --> Language" which I set to spanish and it seems it does nothing, as the map still is shown in cyrilic and puremaps interface in english
![image](https://user-images.githubusercontent.com/2266612/87283458-9be92180-c4f5-11ea-8d2e-18c7c84306a4.png)

**Comment by rinigus** [comment]
Sounds like you selected "Sputnik" as a map provider. As it is Russian provider, they have map tiles in Russian. You can switch to other providers in Main menu/Maps

**Comment by adocampo** [comment]
:man_facepalming:  That was! I did not choose, or don't remember to choose that provider, but it could be, as I tried puremaps months ago and didn't open it until today.

Thank you!
