### ISSUE TITLE
Map orientation during navigation when route is lost

### ISSUE THREAD

**Issue by bokf** [rinigus/pure-maps#407]
When navigating a route I noticed on route loss, that the map orientation is not any more according driving direction, but the map is turning North up? Possibly the map orientation during navigation of a route is not according driving orientation but according route direction? This could explain the behaviour. It would be helpful especially in an unknown city, if the map orientation would turn to "according driving direction" when route is lost. I have "Auto-center on" and "Auto-rotate on". Maybe somebody else has noticed this behaviour?

**Comment by rinigus** [comment]
I wonder whether it turned up north or was following your movement? It is expected that the map will orient itself according to the following list:

- on the basis of your last positions, map match it to streets / paths using osm scout server. if server is not working then
- if close to route,  orient according to the route
- if away from route, orient using last few locations to your movement
- if on foot/bicycle and exploring map (not navigation mode), orient by compass and device orientation

So, were you in navigation mode or exploring the map? I.e., did you start navigation by pressing "start" and without pausing/stopping it?

**Comment by bokf** [comment]
I was in navigation mode starting with the play symbol. Map turned into 3D mode, when I left the route the map turned 90 degree and my moving direction was from left to right. May be it was an accident, that it was showing north up, I did not check if it was exact north, as I was driving ...

Possibly I was still too close to the route, as I was driving on a parallel road? Distance to the route was aprox. 100m? And it did not initiate re-routing.

So I see in your description, it should orient according to the last few locations of the movement. I will make some more tests and will report again.

**Comment by rinigus** [comment]
Rerouting is not initiated immediately to avoid too many server calls. Sounds like it may have been by chance, but let me know how the testing goes.

**Comment by rinigus** [comment]
Any update on this?

**Comment by bokf** [comment]
Today I did a new test leaving the route. Orientation seems to be according route. If I am leaving the route the opposite direction of the route, the map is oriented 180 degree opposite to driving direction (remains according to route). Re-routing supposes a U-turn and map remains 180 degree "wrong" to driving direction. At this point the map is useless, because on the small screen its not possible to see what's coming up (because it is down on the map). Furthermore my brain is used to have driving direction up and not down. I have to wait until re-routing has been performed. Due to an expected U-turn route is showing screen up, driving direction down. Its difficult to explain, I send you some screenshots per PM.

Maybe it would help to prohibit U-turns? And turn the map according driving direction even after leaving the route less than 120 meters?

**Comment by rinigus** [comment]
Should be fixed in the next release - 2.1. Reopen if not
