### ISSUE TITLE
Does not show all OpenStreetMap search results

### ISSUE THREAD

**Issue by Talkless** [rinigus/pure-maps#415]
Hi,

Try searching "H2auto" (self service car wash network in Lithuania) in openstreetmap.org:
https://www.openstreetmap.org/search?query=h2auto

You'll get total 18 entries (after clicking "more").

Now try that in uNav app (Ubuntu Touch) - 17 results (not yet synced in all servers?)

Meanwhile in PureMaps (Ubuntu Touch) I get only 7 results.

Is this limited intentional or..?

**Comment by Talkless** [comment]
> In Pure Maps, which provider did you use?

It's says "Using Photon" in seach window.
Map itself is OpenTopoMap.

**Comment by rinigus** [comment]
Then it is a limit imposed by Photon. Try to search   for some specific one, like in a city or region, to get the one you want

**Comment by rinigus** [comment]
As such, it is not Pure Maps bug, closing

**Comment by Talkless** [comment]
> Then it is a limit imposed by Photon. Try to search for some specific one, like in a city or region, to get the one you want

I see. Thanks for explanation.
Maybe worth adding backend that uNav uses then?

**Comment by rinigus** [comment]
Well, Photon has many advantages like find-as-you-type. As we usually search within some region, it is OK to show the closest car washes and not list all of them available in the world. You are welcome to try other geocoders (search providers) available and see if any of them fits you better.

In practice, you probably want to find a car wash next to some location. For that, you could use "Nearby" search

**Comment by Talkless** [comment]
Yeah, I guess that makes sense, no need to over-complicate.
