### ISSUE TITLE
Applications warns about Mapbox API key being missing even if default provider is not Mapbox

### ISSUE THREAD

**Issue by Newbytee** [rinigus/pure-maps#427]
Currently, even if the default basemap provider was not set to Mapbox at compile time, Pure Maps still displays a warning on first open that you are missing a Mapbox API key. Ideally the user shouldn't have to concern themselves with what an API key is and just be able to use the app without this warning (unless they attempt to use Mapbox), and as such I suggest that this startup warning only should appear if Mapbox is set as the default basemap provider.

**Comment by rinigus** [comment]
It is a correct warning. Mapbox provides also fonts for rendering labels (such as POIs created by users) and it is non-optimal to miss Mapbox API key. Unfortunately, I am not aware of any font provider that allows to get fonts without API.

Exception to such API requirement is OSM Scout Server. That one can provide fonts as Mapbox does. So, it is not really a bug, but an expected warning

**Comment by rinigus** [comment]
PS: While closed, feel free to comment and state that it should be reopened if you think so.

**Comment by craftyguy** [comment]
> Unfortunately, I am not aware of any font provider that allows to get fonts without API.

This question is somewhat naive, but why can't you just fall back to using local fonts?

**Comment by rinigus** [comment]
The fonts are processed and prepared for showing using mapbox gl. See https://github.com/rinigus/mapbox-gl-fonts used to generate fonts for osmscout server.

**Comment by craftyguy** [comment]
how do other projects, like osmand for android, get around this? or are they using the mapbox api for fonts too?

**Comment by rinigus** [comment]
others probably either don't use gl glyphs like that, or bundle them.

maybe we should approach it somewhat differently: 
- find some online mapboxgl tiles provider that packagers are wishing to enable by default
- if none, see if we can require osm scout server or bundle the fonts

bundling fonts may need making small http localhost server, as I am not sure I can get mapboxgl to load fonts from disk directly.
