### ISSUE TITLE
Not possible to install on sfos 3.2 - glibcxx_3.4.21 error

### ISSUE THREAD

**Issue by PizzaProgram** [rinigus/pure-maps#433]
If I try to install to SFOS 3.2.0.12 Torronsuo (device: Xiaomi Redmi 5 Plus),
following error is dropped:
libstdc++.so.6(glibcxx_3.4.21) dependency for harborur-pure-maps-2.0.0-1.2.1.jolla.armv7hl can not be installed.

Same error, if I try to install mapboxgl seperately.
libstdc++.so.6(glibcxx_3.4.21) dependency can not be installed for mapboxgl-qml-1.7.5-1.57.1.jolla.armv7hl

(The error messages are in hungarian language, so my translations may differ a bit.)

**Comment by rinigus** [comment]
You can install an older version using OBS: https://build.merproject.org/project/show/home:rinigus:maps . For that, use http://repo.merproject.org/obs/home:/rinigus:/maps/sailfish_3.2.1.20_armv7hl/ repository.

**Comment by rinigus** [comment]
Due to gcc update in 3.3., I decided to drop support for older SFOS releases and focus on the newer ones. Note that with Pure Maps, you would have to install mapboxgl-qml and then download Pure Maps from OpenRepos. NB! Pure Maps versions <2.0.0

**Comment by PizzaProgram** [comment]
**Thanks** for the quick answer!  
  
So basically you **knew** this will happen, and will break the app on ALL phones pre 3.3 ?  Hmmm....  
At least a big red:   **"WARNING!!! Do not install/update if your OS < 3.3 !!!"**  
... sentence on the top would have been nice here:  
https://openrepos.net/content/rinigus/pure-maps  
  
### May I ask:  
- Would it be too difficult to publish 2 different versions, so people can see:  
"Pure Maps sfos<=3.2"     >> and that would have auto-installed the older repo?  
  
- Are repos overwritten too, or are there many different versions in many subfolders?  
- Do I need to uninstall the current repo first? I yes, How?  
- What happens if I install an other app you wrote? ... Will the old be overwritten and I have to start everything again?  
_ (Sorry, but I'm just a delphi developer, and no idea about linux. I'm just trying to **USE** my phone, not finetune it day by day by day. Anyway there will be no newer version to this model. sfos3.2 is the latest.)_  
  
Or can you please rename the current app to **"PureMaps os3.3+"** ... and put back the old one as it was?  
  
Storeman is auto-upgrading the apps >> so no chance to revoke. :(   >> and it will break the app again and again whenever I click "update all".  
  
_Sorry my frustration, but all this is so overcomplicated and difficult.   
Most of us, "normal users" have no time, no skills, no energy to decipher things like that. We just want to CLICK & RUN.  
No wonder the SFOS user number isn't growing..._

**Comment by rinigus** [comment]
I am doing it at my free time and, as you could see at OBS, it requires work on many packages. This is not to factor in work on offline maps - import of them and work with all related issues. Right now, as OBS does not support 3.4. SFOS, the only usable version is 3.3. As soon as it is updated on OBS, I will make new packages for 3.4. users and keep 3.3. alive as well.

As for adding notes regarding old SFOS versions, no, I am not going to do that. It is known overall that older versions are not supported by apps or can break. If you wish to keep point-and-install, use the up-to-date device. I am not going to add more to my workload and try to support workarounds that I used to be able to compile all for SFOS <3.3. If you wish to do so, code is open, scripts are all out there. 

I am closing this issue as it is not going to be worked on from my side and I don't know anyone who would take initiative, time, and invest some effort into solving it.
