### ISSUE TITLE
FR: Start navigation without a fixed lock

### ISSUE THREAD

**Issue by boriseto** [rinigus/pure-maps#434]
If possible to start navigation right away with some ransom poi to begin with near destination until a gps fix haa been aquired? It would help when in a hurry to set a destination and wait leave the phone recalculate the path to it without having to wait for user input.

**Comment by rinigus** [comment]
It is possible already. Have you tested it?

**Comment by boriseto** [comment]
When I choose a point on map, I have to wait to get a fix until the start button is available.
Random point clicked on map
![screenshot20201120_121320310](https://user-images.githubusercontent.com/396355/99794031-d9a42980-2b29-11eb-8bb9-86142c556cc7.png)

**Comment by rinigus** [comment]
You can tap on "Current position" and select some other location from the search. then it will be possible to calculate the route and start navigation with it.

**Comment by boriseto** [comment]
Huh, didnt think of that, okay, thanks.

**Comment by boriseto** [comment]
Still not a good solution though, I have to enter there and find a poi by searching (it doesn't list anything else but "current location" there, because I don't have a fix).

**Comment by boriseto** [comment]
It isn't that I'm bashing the app, I like it very much how it works, it's just that quirk that isn't like the others.
I'm comparing it to some Android counterparts in which you set up navigation and it will start right away, so you can just leave the phone and start driving, so whenever it gets a fix on GPS, then it will start navigating, you don't have to worry about that in the background.

**Comment by rinigus** [comment]
It looks to me this is a "feature" of Ubuntu Touch. On Sailfish, even without a fix, I have old position available as provided by OS. So, I can do exactly what you want - from that navigation screen select destination and start driving immediately. Maybe someone from UT side can tell whether location can be cached by OS with some knob?

**Comment by boriseto** [comment]
I see, well I'll contact some of the devs there to see if it can be fixed with that.

**Comment by rinigus** [comment]
Closing as it is expected to be provided by the system. Reopen if it turns out to be not true.
