### ISSUE TITLE
Add s2geometry to Ubuntu Touch

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#437]
As new navigation module requires s2geometry, build scripts have to be adjusted. 

Fix #436 first to be sure that example works. Then it will be easier to adjust clickable as well.

**Comment by rinigus** [comment]
@jonnius, Flatpak has been tested now and looks to be working.

In UT packaging, we need to add s2geometry, similar to (see build and clone instructions below)

```        {
            "name": "s2geometry",
            "buildsystem": "cmake-ninja",
            "config-opts": [
                "-DBUILD_PYTHON=OFF",
                "-DBUILD_TESTING=OFF",
                "-DBUILD_SHARED_LIBS=ON",
                "-DBUILD_EXAMPLES=OFF"
            ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/rinigus/s2geometry.git",
                    "branch": "main",
                    "commit": "c33eb5451ff9fec97fc16a711a3b0e0e70a145bb"
                }
            ]
        },
```

For S2 libs and includes, `qmake` config for Pure Maps build should be something like

```
qmake PREFIX=/app CONFIG+=install_gpxpy FLAVOR=kirigami S2INCLUDES=/app/include S2LIBS=-L/app/lib ...
```

Please adjust path for vars as needed.

@jonnius - please let me know if you hit any problems with it.

**Comment by jonnius** [comment]
Thanks for your preparation. It was very easy this way. :+1:
