### ISSUE TITLE
Missing layer with street names / labels

### ISSUE THREAD

**Issue by langfingaz** [rinigus/pure-maps#442]
Thanks for this great, mobile friendly app. My PinePhone has arrived and I couldn't wait to try out this app on a phone!

---

**Bug description:**

With the default `mapbox` map selected there are no street names or labels visible on the map, see screenshot:

<a href="url"><img src="https://cloud.privacy1st.de/s/778PF8oXiQBNWje/preview" align="center" width="200" ></a>
<a href="url"><img src="https://cloud.privacy1st.de/s/jAMtRy7MXF22tnX/preview" align="center" width="200" ></a>

Note: The same is also the case when using offline maps via OSMScoutServer.

**Log from app startup:**

```
Current locale: en_US
Translation not found
Fallback icons at /app/share/io.github.rinigus.PureMaps/qml/icons/fallback
Got library name:  "/app/usr/lib/qml/io/thp/pyotherside/libpyothersideplugin.so"
qt.positioning.geoclue2: Already running
qt.positioning.geoclue2: Already running
file:///usr/lib/qml/org/kde/kirigami.2/ContextDrawer.qml:79: TypeError: Cannot call method 'hasOwnProperty' of null
[ INFO ]  "{unknown}[General]: GPU Identifier: Mali400"
```

**Version**: 2.0.0 (via flathub)
**OS**: [Arch Linux ARM](https://github.com/dreemurrs-embedded/Pine64-Arch/releases/tag/20201112)

---

For comparison reasons: Screenshot from PureMaps in a small window on my desktop computer (x86). This is how it is __expected to look like__ on the phone as well:

<a href="url"><img src="https://cloud.privacy1st.de/s/EebbkAWqemoCgQ3/preview" align="center" width="200" ></a>

**Comment by rinigus** [comment]
I suspect that you are hitting "Known issues" from https://wiki.mobian-project.org/doku.php?id=puremaps . To my knowledge it happens only on PinePhone suggesting a bug (or bugs) in its drivers. Try to switch to software rendering and see if it helps

**Comment by langfingaz** [comment]
Thanks for the quick reply. Using `LIBGL_ALWAYS_SOFTWARE=1` did indeed resolve the issue for me and I agree that it seems likely that the bug is somewhere else.
Let's hope that other PinePhone users stumble upon this (temporary) solution. I'll close this the as not PureMaps related.
