### ISSUE TITLE
Transition from qmake to CMake

### ISSUE THREAD

**Issue by Newbytee** [rinigus/pure-maps#450]
As discussed on Matrix, we might want to move from qmake to CMake considering that's the direction Qt itself is going[1]. Ringus has stated that he himself is in no hurry to make this transition, but he wouldn't mind if someone else takes up the task of converting the qmake scripts to CMake and contributes this.

[1] https://www.qt.io/blog/qt-6-build-system

**Comment by rinigus** [comment]
Some platforms on which install should work

- [ ] Kirigami
- [ ] Sailfish
- [ ] Ubuntu Touch
- [ ] Flatpak

**Comment by rinigus** [comment]
Now we have only Ubuntu Touch that has to be ported over to cmake.

/cc @jonnius

**Comment by jonnius** [comment]
Successfully tested for Ubuntu Touch.

**Comment by rinigus** [comment]
Transition merged
