### ISSUE TITLE
Share location URL switch to OSM

### ISSUE THREAD

**Issue by sfbg** [rinigus/pure-maps#46]
Why does the share location URL use Google Maps as a link?
Thus, while sharing, I am practically promoting the use of GMaps by others. Something I want to avoid.

Why not OSM.org as default?

**Comment by rinigus** [comment]
Good point. While OSM is not as reliable as GMaps (I had to press reload once in a while on SFOS browser), its probably correct to share using OSM link. Corresponding fix committed already
