### ISSUE TITLE
Remove audio in cache workaround for Ubuntu Touch

### ISSUE THREAD

**Issue by jonnius** [rinigus/pure-maps#467]
The [issue](https://github.com/ubports/media-hub/issues/2) that wouldn't let app's play audio files from temp dir was fixed in Ubuntu Touch. Once [OTA 16](https://github.com/orgs/ubports/projects/25#card-50989623) is out, we should remove our current workaround storing audio files in cache dir.

Reminder: We should investigate whether temp dir is in RAM.
Answer: app's temp dir is of type tmpfs, so it is in RAM.

**Comment by jonnius** [comment]
OTA-16 is out and we can merge this.

**Comment by rinigus** [comment]
Done, thank you!
