### ISSUE TITLE
turn off Auto-rotate option completely

### ISSUE THREAD

**Issue by Pohli** [rinigus/pure-maps#47]
I almost never use this option 'cause I'm used to read oldschool maps where north is at the top. But as soon as I start, pause and resume navigation or reroute Auto-rotation is turned on again and I have to deactivate it manually every time (there should be a note at the setting that it's not for navigation mode like there is at the Snap position to road setting).
So either this option should be valid globaly (also in navigation mode) or there should be the same option again when starting navigation, also remembering the setting after a restart of Pure Maps.

**Comment by rinigus** [comment]
Agreed, this should be changed. I'll probably add it to Navigation options
