### ISSUE TITLE
Navigation calculation with traffic and updating the caclulation regularly

### ISSUE THREAD

**Issue by dexic79** [rinigus/pure-maps#485]
On my daily commute in the area of Stuttgart in Germany, it would be very nice to have a calculation based on traffic information, just as GMaps does it.

**Comment by rinigus** [comment]
In my understanding, the best chance for it is to start supporting HERE fully (#275). I am not sure if Mapbox also provides such service, could be.

**Comment by mirror176** [comment]
https://www.mapbox.com/traffic-data/ says they do, and they mention at the top and bottom of different formats for native openstreetmap data matching and a more general form if applying to other maps.

**Comment by mirror176** [comment]
In their information at the bottom, they say it can be used for offline with the 'typical' (=based on historic data) instead of 'live' data though they also say users of traffic data have to submit anonymous gps data to mapbox too; not sure how submit+offline is planned to be required by them.

**Comment by rinigus** [comment]
We are using REST API with Mapbox (not their Android or iOS targeting Navigation API). So, question is how it would work with our approach.

**Comment by rinigus** [comment]
Maybe it is possible, looking at https://www.mapbox.com/pricing/
