### ISSUE TITLE
Check if GPX router is broken

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#492]

**Comment by hankschwie** [comment]
gpx router works in pure maps version 2.3.0; it does not work anymore in version 2.4.0. I use pure maps with OSM scout server on ubuntu touch on an bq m10 fd, (dev) with version 2.4.0. The older version worked fine, and still does on my  fairphone2. Both use up-to-date maps for the OSM scout server.

Is there an easy way to go back to the older version untis this issue has been fixed?

**Comment by jonnius** [comment]
You could build it yourself.
```
git clone https://github.com/rinigus/pure-maps.git -b 2.3.0 --recursive
cd pure-maps
```
and then follow the instructions in [README](https://github.com/rinigus/pure-maps/blob/master/packaging/click/README.md) (building can take a while).

**Comment by rinigus** [comment]
I am going to release bugfix release
