### ISSUE TITLE
add support for OpenSlopeMap

### ISSUE THREAD

**Issue by henning-schild** [rinigus/pure-maps#496]
OpenSlopeMap offers tile downloads in `mbtiles` format for offline usage. For online usage it should just be a matter of adding it and finding the right parameters for such a json file.

In fact this might be interesting at an even more abstract level:
 - adding support to add maps with a dialog (any maps really ... that follow the tile URL pattern most of them have in common)
 - adding support to "open" "mbtiles" files

**Comment by henning-schild** [comment]
These maps are especially interesting for mountain regions, relevant for avalanche risk estimation. These areas tend to have bad coverage, so offline would be kind of important. Or caching of areas previously looked at ...

**Comment by rinigus** [comment]
I cannot find description of API nor how to get that map into application. Based on https://www.openslopemap.org/installation-auf-ios-bzw-android-fuer-osmand/, it is actually raster tiles pushed into SQLite database or requested online. 

In principle, online should be simple. Look at maps subfolder for examples.

For offline, probably some small server would make sense. Or maybe see if tiles can be served directly to mapbox gl. Would have to check it.

**Comment by henning-schild** [comment]
I did look at that subfolder for online, and it indeed looks rather simple. Just did not look into building, which is probably less simple.

For offline i installed "OSM Scout Server" but it looks like it can not just serve the files we can get from that project.

**Comment by rinigus** [comment]
For extending, you don't even need to build it. It is sufficient to add new plugin as described in README in that folder. 

For offline, we will have to think a bit. In principle, I can write small extension for OSM Scout Server allowing you to serve these tiles via it. Alternative is to use something like https://github.com/DenisCarriere/mbtiles-server . Could be that the used widget allows to access the tiles directly as well - need to investigate

**Comment by henning-schild** [comment]
Sweet, i will look into adding that online case on my phone. If there is some sort of caching that might be good enough for a start.

As i said, i think that whole issue can be seen as pretty generic, potentially eventually allowing additional maps for everyone ... as opposed to that example i happen to be interested in at the moment.

**Comment by henning-schild** [comment]
Maybe i am blind, but https://github.com/rinigus/pure-maps/blob/master/README.md does not seem to tell me how to add more online maps. Can you point out the section i seem to be missing?

**Comment by rinigus** [comment]
Sorry, should have pointed to the correct one: https://github.com/rinigus/pure-maps/blob/master/maps/README.md
