### ISSUE TITLE
Screens fails to stay on with latest Ubuntu Touch qt5.12

### ISSUE THREAD

**Issue by poVoq** [rinigus/pure-maps#498]
After updating to the latest qt5.12 dev release yesterday, I noticed a regression that results in the screen turning off after a short while when navigating. Obviously that should not be the case ;)

**Comment by rinigus** [comment]
Sounds like https://github.com/rinigus/pure-maps/blob/master/qml/platform.uuitk/ApplicationWindowPL.qml#L43 does not work in qt5.12 then. I presume it is a bug on Ubuntu side. Or some new API was developed for it. Maybe UT devs can help?

**Comment by poVoq** [comment]
Seems like a fix (Ubuntu Touch side) is on the way. Thanks for looking into it anyways.

**Comment by rinigus** [comment]
You're welcome. Closing it over here
