### ISSUE TITLE
No "snap to road" box/switch in settings

### ISSUE THREAD

**Issue by edw-edw** [rinigus/pure-maps#521]
Hello, first of all, I would like to say thank you for the very niche App! It is a good thing to have a navigation App with offline maps!
Installation of OSM Scout Server for that was no problem and works fine, even though I get an error message of Pure Maps on start up "Problem with Maps" from time to time, which can be solved by installing or uninstalling(!) any map in OSM Scout Server. (but that could be a problem of OSM Scout Server)

Now I'm trying to get the speed limit appear on the navigation map.
Profile is "Offline" with maps installed in OSM Scout Server running in the background .
In settings under "navigation" the "speed limit" is greyed out but set to "always"
To get the speed limit shown, one have to activate "snap to road", but there is no box whether under "navigation" nor under "explore" (which is empty at all).
Profile was also set to online and same thing here: still missing the box/switch.

I had a look at the "PreferencesPage.xml" and there ist an entry in the
"ExpandingSectionPL {
id: sectionNavigate
...
TextSwitchPL {
id: mapmatchingSwitch
...
text: app.tr("Snap position to road")

"ExpandingSectionPL {
id: sectionExplore
...
ComboBoxPl {
...
label: app.tr("Snap position to road")

but nothing in the settings to find there

Are there any hints what could be the reason for the missing box?
Thanks in advance for any help!

Cheers edw

Language German (therefor may be some identifiers may differ in my back translation to english)
Device One Plus One
Ubports Ubuntu 16.04 (OTA-15) 20201208-1616

**Comment by rinigus** [comment]
In Ubuntu, map matching is absent as there is no way to make DBus calls between two clickable apps. This is in contrast to regular Linux even with Flatpaks. Map matching is using DBus for making 'snap to road' possible.

Please raise the issue with Ubuntu Touch developers so they would allow such communication.

**Comment by edw-edw** [comment]
Hello rinigus!
That was a very fast response :-)
Thank you for the explanation! I will bring this up on the board for the UBports issues.
A note for UBports users on the Open Store Site of Pure Maps would be nice (I fiddled with this a long time...) .
Cheers edw

**Comment by rinigus** [comment]
/cc @jonnius - regarding note

I am closing it here as not much can be done on this side of the fence.

**Comment by jonnius** [comment]
What would be an appropriate note on the Open Store page? I am not sure people will understand what "map matching" is about. Maybe something like the following?
"Note: The snap-to-road-feature is not available in this package."

**Comment by rinigus** [comment]
Yes, that sounds good. Not many know map matching term

**Comment by jonnius** [comment]
Ok, it is added to the description on the Open Store.

**Comment by edw-edw** [comment]
Hello rinigus and jonnius.
Thanks for the work on bringing this onto the open store. The wording "no snap to road" shall be clear for everyone.
If there is anything I could help with, e.g. translate into German, please feel free to ask for!
Cheers edw

**Comment by jonnius** [comment]
Writing docs, issues and translation help is always welcome. For translations: https://www.transifex.com/rinigus/pure-maps/

**Comment by edw-edw** [comment]
Ok, I translate what there was left untranslated, except #135 "(D)" and #136 "(W) cause that are actually no phrases.

**Comment by jonnius** [comment]
Thanks! As you mentioned "writing docs", there is a [Pure Maps Page](https://rinigus.github.io/pure-maps/) that still does not contain much information. Also see #400 and [here](https://github.com/rinigus/pure-maps/tree/master/docs) one can contribute. As you seem to be german, the [ubuntuusers wiki page](https://wiki.ubuntuusers.de/Ubuntu_Touch/Pure_Maps/) could serve as inspiration.
