### ISSUE TITLE
Hearing nautical terms while navigating traffic

### ISSUE THREAD

**Issue by kwoot** [rinigus/pure-maps#525]
Hi,

I used this app for the first time on Ubuntu Touch and can't help but notice some nautical terms.
Like, "turn to starboard" and "turn to port". I guess these should be "right" and "left".
I could not find these strings in the checked out code so I do not know how to fix them.
But since not everybody driving a car while navigating traffic is also a sailor I guess it would be an idea to change these.
And, if it's easily fixed with one of the many settings, please tell me which one. And maybe, IDK, change the default? :-)
Kudos on an awesome app btw.
Regards, Jeroen

**Comment by rinigus** [comment]
Hi,

this should not be default. For some reason, you have "English Pirate" set as a language for your routing. To change, calculate route again, but set language to English. Language is one of the settings that you set while on navigation page. Routers supporting "Pirate" language are OSM Scout Server and Stadia maps - both based on Valhalla.

Now I wonder whether language defaults got messed up somehow. I presume you didn't change it yourself.

Cheers, Rinigus

**Comment by kwoot** [comment]
Version: 2.6.0
Had to look some stuff up. 
Routing Engine: Default setting: Stadia Maps. 
Preferences: 
-menu General: Units metric, Language: Dutch
-menu Testing: Selected voice engine: Mimic, English, Male
-menu Navigation: voice gender: female

Where can I find the language setting to change? Maybe I changed it in error but would be nice to know where I did it :-)

**Comment by rinigus** [comment]
Looks like it the question asked more frequently that I like it (twice in recent weeks). Routing language is hooked to the route that you calculate. So it is under

Main menu/Navigation and one of the options. 

The language option and a bunch of other ones will open only after you select destination. This is done to avoid killing users with too many details.

**Comment by kwoot** [comment]
Ah yes, after starting a route and pausing and opening the navigation menu I can see that the language is set indeed to "English Pirate". If there had been more "arrr"-like sounds in the audio I might have suspected this sooner :-).
