### ISSUE TITLE
Install fails with 'Nothing provides libcrypto.so.1.1'

### ISSUE THREAD

**Issue by poetaster** [rinigus/pure-maps#527]
This is a Vollaphone with 3.4. I had pure maps installed and functional. Reflashed and it seems a new version of pure maps...

I have /lib/libcrypto.so.10 and /lib/libcrypto.so.1.0o.... I'm guesing this is now only SFOS 4?

**Comment by poetaster** [comment]
Just to confirm that 2.6.0-1.15.1 installs and works.

**Comment by rinigus** [comment]
@poetaster: looks like it is induced by SFOS upgrade for 4.0. 

I have compiled apps for older versions, but they are distributed via OBS at https://build.merproject.org/project/show/home:rinigus:maps

Try to grab Pure Maps for 3.4 from there and let me know if it works for you.

**Comment by poetaster** [comment]
Thanks, I'll git it a go once I fix my Volla :)

**Comment by rinigus** [comment]
Closing
