### ISSUE TITLE
Audio does not go through Bluetooth

### ISSUE THREAD

**Issue by antoyo** [rinigus/pure-maps#538]
Hi.
I use Pure Maps on Sailfish OS and I'd like to send the voice instructions to my car speaker via Bluetooth, but it seems to not happen automatically.
Other applications like the video player seems to do so automatically, but Pure Maps doesn't seem to and I can't find an option to send the audio output to bluetooth.
So, how can I send the audio output to bluetooth?
Thanks.

**Comment by rinigus** [comment]
I suspect it is an issue with recent versions of SFOS. I would have to report it and see if there is some reasonable solution.

**Comment by antoyo** [comment]
I have SFOS version 4.0.1.48 (Koli).

**Comment by rinigus** [comment]
I have seen the same and I think it started a SFOS version or two before
