### ISSUE TITLE
Bogus speed and direction with the geoclue2 position backend

### ISSUE THREAD

**Issue by tpikonen** [rinigus/pure-maps#545]
I'm using Pure Maps 2.7.5 from flatpak on Pinephone / mobian.

The speed indicator shown during navigation is showing a constant value of '4 km/h', despite the GPS unit reporting an accurate speed value.

Pure Maps also does not start the GPS by itself, but when GPS values are requested by another application, Pure Maps also gets the GPS position values. This is possibly a variant of #114.

**Comment by rinigus** [comment]
Disclaimer: I don't know much about Pinephone and its Linux distros, mainly from bug reports. So, treat response accordingly.

Sounds like some issue with hardware adaptation. Namely, it is strange that Qt location request does not start GPS. Pure Maps is using speed provided by Qt location module and it is possible that something is not hooked into it on your platform.

When you mention 'GPS unit' - is it via some other program?

**Comment by tpikonen** [comment]
Yeah, this definitely looks like a Qt problem, but I thought you might have some insight.

I have a program which requests GPS NMEA data from ModemManager via D-Bus. This starts the GPS and eventually gets a fix, and the speed values there seem to be correct. The speed values apparently do not reach Qt, but position does.

Pure Maps works fine as a (bike) navigator on the Pinephone, as long as one keeps the GPS on with another program, but it would obviously be nice to have it working out of the box.

**Comment by rinigus** [comment]
Closing here as it is not Pure Maps issues. Please reopen if it will be clear to be otherwise

**Comment by rinigus** [comment]
That was a really silly code in qt plugin! how didn't I catch it before that they declared a var in if statement... and what for (ok this can continue for a while). do you hope that it will get accepted in debian? what about submitting it upstream to Qt?

**Comment by tpikonen** [comment]
Let's see if the Debian maintainer responds. If that does not happen in few days, I'll submit it upstream.

**Comment by rinigus** [comment]
@tpikonen: your fix made it in today upstream into Qt. Thank you!

**Comment by tpikonen** [comment]
Cool! Thanks for opening the bug report.
