### ISSUE TITLE
Map wishlist

### ISSUE THREAD

**Issue by kkofler** [rinigus/pure-maps#557]
The following is a list of map providers I would love to see added, especially now that the Thunderforest maps no longer work:
* https://www.openstreetmap.org/ – the default Mapnik/CartoCSS rendering. It has a lot more details than Mapbox or Sputnik.
* https://www.cyclosm.org/ – the FOSS alternative to OpenCycleMaps.
* https://www.xn--pnvkarte-m4a.de/ – public transport map (much better than Thunderforest Transport anyway).

Would you be interested in pull requests adding some or all of the above? Or were they already vetoed by the server infrastructure providers?

**Comment by rinigus** [comment]
Sure, we can add those. Some time ago it OSM.org was not intended to be used by apps. I don't know if this has changed recently. 

Please check use conditions. If they are fine, sure let's add them. PR will be welcome.

**Comment by kkofler** [comment]
Looks like for openstreetmap.org and cyclosm.org, the following policy applies: https://operations.osmfoundation.org/policies/tiles/
So adding this to the app needs to be discussed with the Operations Working Group: https://wiki.osmfoundation.org/wiki/Operations_Working_Group – not sure whether those are also responsible for cyclosm.org (which links to the osmfoundation.org policies), or whether we need to contact somebody at OpenStreetMap-France (who are the ones actually hosting that site).
For ÖPNVKarte, the terms in German also say that heavy usage needs to be discussed with the owner, Melchior Moos.

Some FOSS mapping applications such as Marble and GNOME Maps have been granted permission to use the openstreetmap.org tiles. (Marble also offers ÖPNVKarte as a downloadable add-on map, where the add-on download is of course just the configuration for the web service.) What I cannot tell is whether Pure Maps will qualify, since it apparently now has enough users to upset Thunderforest. I guess the only way to find out is to ask.

**Comment by rinigus** [comment]
Question that will be raised is the number of users. Which I don't really know, unfortunately. However, For Thunderforest, we had tile downloads at the order of 250000 tiles/month. Maybe that's an order of magnitude which gives some kind of indication.

Would you mind to get in touch with them and ask for permission?

**Comment by kkofler** [comment]
Sure, I can do that.

(As a note for the applications I mentioned: GNOME Maps is both desktop and mobile, but for Marble, we are talking only about the desktop version of Marble here. The mobile version Marble Maps is very minimal and currently supports only the vector tiles that are distributed on kde.org infrastructure and rendered on the client side, I have not seen any setting to switch to one of the raster tile providers.)

**Comment by rinigus** [comment]
Interesting that Gnome Maps swapped to OSM. I was sure they used Mapbox earlier. 

Thanks for the initiative and good luck with the discussion!

**Comment by kkofler** [comment]
No, sorry, I dropped the ball there, thanks for the reminder.

**Comment by Talkless** [comment]
I would be really usefull to have OSM tiles. I use Pure Maps to bookmark various places to be later edited into OSM database (via JOSM editor). But since we don't have OSM tiles with all visible amenities (like shops, tourist attractions, other), I don't really know if it was already mapped or not.

I can keep switching between openstreetmap.org in the browser and PureMaps, but that's inconvenient and actually bug-prone, as switching apps makes Ubutnu Touch crash.. :-| .

Maybe we could use OSM tiles only for logged-in OSM user?

**Comment by rinigus** [comment]
Let's see what comes out of @kkofler contact with OSM

**Comment by Karry** [comment]
@kkofler was there any response? Looking the usage policy, I should negotiate permission for tile usage in OSM Scout too...

**Comment by kkofler** [comment]
I wanted to take the time to formulate polite and to the point e-mails, but somehow the perfect has been the enemy of the good and I still have not gotten around to it. This makes me kinda sad because I really wanted to move things forward and failed, I have only been the roadblock in this issue.

**Comment by kkofler** [comment]
(To be clear, there cannot be any response because no inquiry was sent, at least not by me.)

**Comment by kkofler** [comment]
Does the following sound like reasonable? If so, I will try to send it before everyone goes on vacation. Or do you have any suggestions on how to improve the wording?

```
Subject: Request for permission to use [map name] tiles in Pure Maps

Dear [project name] administrators,

I am writing this e-mail on behalf of the Pure Maps project
[https://rinigus.github.io/pure-maps/]. Pure Maps is a Free / Open Source
Software (FOSS) application (licensed under the GNU General Public License
(GPL) version 3) for Sailfish OS and GNU/Linux (with focus on mobile devices)
to display vector and raster maps, places, routes, and provide navigation
instructions with a flexible selection of data and service providers. As
such, availability of online maps is crucial for Pure Maps to provide its
functionality. However, as a non-commercial project, Pure Maps cannot afford
to buy expensive paid API keys from commercial map tile services, nor do we
have the resources to host our own tile server.

In particular, we are interested in the [map name] map tiles served at [map 
URL], for which you appear to be the point of contact for application 
developers seeking to use the map in their applications. We would like to 
kindly request the permission to show this map in the Pure Maps application. 
In other words, our question is whether and under what conditions it would be 
permissible for Pure Maps to offer your online bitmap map tiles to end users.

Note that, being an application for niche platforms (Sailfish OS and mobile 
GNU/Linux), we do not expect Pure Maps to ever generate the amount of traffic 
a popular Android or iOS app would produce. Pure Maps did, however, in the 
past, exceed the limits of the free plan of at least one commercial tile 
provider, causing it to get blocked. The tile downloads measured there were 
at the order of 250 000 tiles per month, so this is the order of magnitude to 
expect. Since Pure Maps does not send tracking telemetrics (e.g., to count 
the number of distinct users) to a central server, that is unfortunately the
most accurate metric we can provide.

Kind regards,
        Kevin Kofler, user and potential contributor to Pure Maps,
        on behalf of the Pure Maps project
```

**Comment by rinigus** [comment]
No problem, some times it does take longer than expected. It looks good to me, let's send it out.

**Comment by Talkless** [comment]
Looks pretty good @kkofler .I would like to suggest adding UBPorts as another niche mobile FOSS OS where it's also used.

also, maybe I would change:
> request the permission to show this map in the Pure Maps application

to:

> request to use tiles from this map server in the Pure Maps application

..or similar.
"show map" is kinda too vague IMO.

But overall, pretty good job!

**Comment by kkofler** [comment]
@Talkless: I have tried to incorporate your suggestions into the wording, does this sound better now?

```
Subject: Request for permission to use [map name] tiles in Pure Maps

Dear [project name] administrators,

I am writing this e-mail on behalf of the Pure Maps project
[https://rinigus.github.io/pure-maps/]. Pure Maps is a Free / Open Source
Software (FOSS) application (licensed under the GNU General Public License
(GPL) version 3) for Sailfish OS, UBPorts (Ubuntu Touch), and other mobile
GNU/Linux environments (Plasma Mobile, Phosh, Sxmo, etc.; using the Kirigami
framework) to display vector and raster maps, places, routes, and provide
navigation instructions with a flexible selection of data and service
providers. As such, availability of online maps is crucial for Pure Maps to
provide its functionality. However, as a non-commercial project, Pure Maps
cannot afford to buy expensive paid API keys from commercial map tile
services, nor do we have the resources to host our own tile server.

In particular, we are interested in the [map name] map tiles served at [map 
URL], for which you appear to be the point of contact for application 
developers seeking to use the map in their applications. We would like to 
kindly request the permission to display map tiles from your tile server in
the Pure Maps application. In other words, our question is whether and under
what conditions it would be permissible for Pure Maps to offer displaying the
bitmapped map tiles from your online tile server as a map choice to end
users.

Note that, being an application for niche platforms (Sailfish OS, UBPorts,
and other mobile GNU/Linux), we do not expect Pure Maps to ever generate the
amount of traffic a popular Android or iOS app would produce. Pure Maps did,
however, in the past, exceed the limits of the free plan of at least one
commercial tile provider, causing it to get blocked. The tile downloads
measured there were at the order of 250 000 tiles per month, so this is the
order of magnitude to expect. Since Pure Maps does not send tracking
telemetrics (e.g., to count the number of distinct users) to a central
server, that is unfortunately the most accurate metric we can provide.

Kind regards,
        Kevin Kofler, user and potential contributor to Pure Maps,
        on behalf of the Pure Maps project
```

**Comment by Talkless** [comment]
@kkofler yes, thanks.

**Comment by rinigus** [comment]
Any updates regarding it?

**Comment by rinigus** [comment]
As it pretty much got stale, closing it here. Reopen if some new info will appear
