### ISSUE TITLE
sharing broken

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#56]
From https://talk.maemo.org/showpost.php?p=1548532&postcount=204

It seems that sharing current location is broken (1.5.0). Sharing to email results in no gecode pickup. If clicking SMS or Other, nothing happends.

**Comment by sfbg** [comment]
It works now.

I do not want to sound as if I am nitpicking, but I do not understand why there should be a Google Maps sharing option from an app that does not use Google Maps data. 

Why not Here Maps instead (considering that it is a layer now).

The best would probably be to share the link to the service that is currently being used. If it is OSM-based then osm.org, if it is a different one like here, then a Here URL and so on.

**Comment by rinigus** [comment]
The reasoning behind Google Maps is simple - its picked up automatically at Android, allowing to its users to navigate to the shared position simply. geo nor OSM are not picked up that way. 

Note that the sharing via Google Maps is optional and is disabled by default. Hence, I will keep it for now as it is
