### ISSUE TITLE
OSMScout server not started automatically

### ISSUE THREAD

**Issue by tpikonen** [rinigus/pure-maps#566]
I noticed that in pure-maps versions 2.8.x the OSMScout server was not started by D-bus activation, but had to be started manually. I use the flathub version of OSMScout and a locally built pure-maps (on Debian bookworm).

In commits before merging of #559 D-bus activation worked, so the problem is somewhere in the new C++ PositionSource.

**Comment by rinigus** [comment]
I wonder whether I forgot to ping DBus to activate it or something similar happened. Will have to look into it.

**Comment by rinigus** [comment]
Looked through the code and tested a bit. Indeed, compared to earlier code, OSM Scout Server should be DBus activated  ONLY if map matching is requested in your case (no systemd activation). Would you mind to check if it is true:

- stop OSM Scout Server
- start Pure Maps

At this stage, the server should not be started

- enable map matching (snap to road) in Pure Maps/Preferences/Navigation. could have been enabled earlier as well
- start navigation in Follow me mode (Routing, select "Follow me" mode and press start)

This should have started the server.

**Comment by tpikonen** [comment]
Thanks for looking into this.

Everything worked as you expected above, except for a small glitch: The Snap to road config widgets were not present at first, because I use the flatpak version of OSMScout server which does not have a command like 'osmscout-server'. I created a script with that name which starts the flatpak version and the config widgets appeared.

The code which needs to be fixed in order to detect the flatpak OSMScout is probably in poor.application.has_mapmatching().

**Comment by rinigus** [comment]
Indeed, combination of flatpak osm scout server + deb pure maps was not considered. There is cmake option `MAPMATCHING_CHECK_RUNTIME` that can allow you to force map matching without checking for the server, but maybe flatpak scenario has to be considered as well. Hmm, maybe I should just drop that code as we can automatically enable it via C++ DBus triggering and there is no need to test for it... I'll check it out.

Meanwhile, with the script over there and having Flatpak based install for the server, you could get auto-activation using internal "listen" mode of the server. See "Automatic via included listen mode" at https://rinigus.github.io/osmscout-server/en/ . That would cover DBus and http requests (tiles, routing, search).

**Comment by rinigus** [comment]
I have dropped now detection of OSM Scout Server installation and DBus activation is tried every time map matching is requested. For cases without systemd activation, the server provides listening mode that should be used. 

I believe that should resolve issues reported over here and I am closing it. Feel free to comment and, if needed, reopen the issue.

**Comment by tpikonen** [comment]
Thanks for the fixes. I tested 2.9.1 in offline mode with OSMScout from flathub and everything starts up and works fine, but if I let pure-maps idle long enough that OSMScout server quits, then it is not restarted again and I get 'Failed to load tile' errors.

Starting OSMScout in listen mode, as you explained above, fixes this, but it is kind of hard to discover for a random user. 

Since pure-maps can start OSMScout and knows when it disappears (there is a `Service disappeared  "io.github.rinigus.OSMScoutServer"` line in the log), would it be possible to also restart OSMScout after idling?

**Comment by rinigus** [comment]
It is not very discoverable, I agree. All I could do is to add that into docs. 

Problem with the server is that you actually want it to shut down without activity to release RAM. As there are two ways that the server can be contacted with (HTTP and DBus), each has to ensure that it can start the server. On Linux systems with systemd support (but not when server is in flatpak), it all works naturally and has a separate Settings options in the server as well. For other cases, as yours, you have to be more involved.

If I start restarting the server via DBus while actually needing HTTP service, logic will get more complicated and we will have some cross-references in the code. For example, stopping the server while you are not using maps (maps are minimized) will be tricky. In this respect, having --listen was a compromise that allows to keep clients (Pure Maps and others) sane.
