### ISSUE TITLE
10m away from road

### ISSUE THREAD

**Issue by bigbiggie** [rinigus/pure-maps#577]
Hi,

I'm using Pure Maps (installed through flatpak) on a Pinephone with Arch Linux Arm installed. Navigation sort of works, that is, I don't get lost and I will find my way to the destination but there are two annoying problems:
- Pretty much all the time I get '10m away from road' message. Wouldn't it be possible to set a wider tolerance to the road? This could be user-defined as an option.
- Another problem I have is that the "car direction" is almost always to the left of the road. I mean, the location symbol always points to the left of the road which is probably a problem of my phone, but anyway: Wouldn't it be possible to force the direction to the route even if it is not the case?

I'm sorry, my english language knowledge is kinda limited, I hope it is understandable ...
Other than that, I have to admit Pure Maps is awesome. Thanks for the work ...

By the way, I'm new to github, I hope this is the right place to post this ...

**Comment by rinigus** [comment]
Yes, it is correct place to file issues and all is clear.

I suspect that the direction is the main problem in your case. I am preparing the new release and it should handle direction calculation better for PinePhone. 10m shouldn't be an issue as far as I remember if direction is fine. So, let's see if the direction calculations would fix it for you in the next release. Just make sure you would let me know over here when you have a chance to test it.

As for timing, it is probably a week away from now. But it is hard to tell precisely.

**Comment by jonnius** [comment]
I have the 10 or even 20 meter away from road situation from time to time, too, on my Xperia X with Ubuntu Touch. Would be happy about a different tolerance, too.

**Comment by rinigus** [comment]
Message was displayed with the distance even when it wasn't a reason for being detected as away from route. This has been just corrected. I would prefer not to overload user and explain why "away from route" was triggered as it could be due to wrong direction, jumping backwards to what is expected direction of travel and such. So, distance will be indicated only when tolerance is exceeded. Currently it is set to 15m, as was before.

I will look into adding user-specified tolerance

**Comment by rinigus** [comment]
It is possible to specify now positioning accuracy under navigation preferences. Considering that it is closed with it.

**Comment by bigbiggie** [comment]
It works like a charm, both the direction as well as the position accuracy (I had to set it to 30m). Tested it today from home to work and back to home. Now I can finally throw away my android device from my car. Thank you so much!!

**Comment by rinigus** [comment]
Great to hear - enjoy!
