### ISSUE TITLE
Notification about lack map provider reappears to fast

### ISSUE THREAD

**Issue by atlochowski** [rinigus/pure-maps#583]
Steps to reproduce

1. Open Pure Maps (default setting is offline maps) without running OSM Scout server
2. Notification about lack map provider appears
3. Swipe notification away
4. Open menu to change maps to online
5. It difficult to change maps to online before reappearing notification

**Comment by rinigus** [comment]
Thanks for reporting!

**Comment by rinigus** [comment]
But that notification also allows you to choose another profile or proceed to settings. Closing here. 

Please reopen if I misunderstood which notification was mentioned.
