### ISSUE TITLE
API key not read until restart

### ISSUE THREAD

**Issue by JulianGro** [rinigus/pure-maps#589]
When starting the latest flatpak, Mapbox is greyed out and marked as "(disabled)".
I assumed it might need an API key so I added one.
It was still disabled.

Turns I needed to restart Pure-Maps to have it read the API key and enable Mapbox.

**Comment by rinigus** [comment]
Message asking to restart Pure Maps after changing/adding API keys is already there. On the top of the API subsection in preferences.

**Comment by rinigus** [comment]
Closing as the message is there
