### ISSUE TITLE
have an "home" option

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/pure-maps#59]
it would be nice to have an option to set an home adress and being able to just click on a button to just have the app set for going back home from where you are. Here has it and to me it's a very nice thing :)

**Comment by rinigus** [comment]
This is fixed now through shortlisted POIs. In the next release, you will be able to shortlist any of your bookmarked POIs and then they will appear next to "Current location" in Routing and Nearby pages. I will later redesign these dialogues, but the functionality is there

**Comment by Pohli** [comment]
I hope it's okay to comment on a closed issue.
I don't see any home option. And what are these shortlisted POIs about? How should it look like? Do I have to activate it first? Where?

Jolla Phone with SFOS 3.0.0.8 and Pure Maps 1.10.0

**Comment by rinigus** [comment]
Absolutely, keep this as a communication channel.

Shortlisted POIs are essentially 'home' or similar functionality. Try to shortlist a POI. For that, in the list of POIs

- long press on POI
- select View
- bookmark POI and shortlist it in View page

Now go to Navigation and press 'To'. Your shortlisted POI will appear above Search field and you could just click on it to select as a destination.

I will have to rework Navigation design to make it more visible, but functionality is there already
