### ISSUE TITLE
#feature_request save route and share route

### ISSUE THREAD

**Issue by datamaskinen** [rinigus/pure-maps#592]
#feature_request

It would be good with an option to save the route i plan and then an option to import a route that i have planed before...

for example if i sit on my home computer and plan a road trip route and then want to upload it to my car-navigator..

It would work with just save as a file and import as a file to sync them between the devices .... or this might already be possible ?

**Comment by rinigus** [comment]
You can already import GPX files and either use them raw or run through router to get instructions. For that, get to routing, choose GPX or GPX Smart as a router and load your file.

Related issue: #412

Would be good if someone would start to work on #400 to introduce these features

**Comment by rinigus** [comment]
Closing as mostly duplicate
