### ISSUE TITLE
No map or interface loaded

### ISSUE THREAD

**Issue by Justinzobel** [rinigus/pure-maps#597]
When running via terminal I get the following output but no map or interface loads.

```
pure-maps 
Current locale: en_AU
Translation not found
Fallback icons at /usr/share/pure-maps/qml/icons/fallback
Acquired QGeoPositionInfoSource: "geoclue2"
Calculate direction using a sequence of coordinates
file:///usr/share/pure-maps/qml/PositionSource.qml:71: TypeError: Cannot read property 'center' of null
QQmlComponent: Component is not ready
```

![image](https://user-images.githubusercontent.com/1370117/158280980-b85d7baa-845e-43b5-83aa-174d8197a61c.png)

**Comment by rinigus** [comment]
Which platform is it? Where did you install it from (distro packaged, flatpak)?

**Comment by Justinzobel** [comment]
Fedora 36 x86_64, compiled from source.

**Comment by Justinzobel** [comment]
Found the spec file in the repo and tried that but I get:
```
CMake Error at thirdparty/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/home/justin/rpmbuild/BUILD/pure-maps-2.9.2/thirdparty/geomag/geomag/model_data/WMM.COF":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:209 (include)
```

**Comment by rinigus** [comment]
You have to clone recursively to get submodules. In your build, have you also installed dependencies, such as Mapbox GL QML plugin?

**Comment by Justinzobel** [comment]
Is it possible to add another asset to the release that includes these submodules? Many Linux distributions do not allow network access during a build.

**Comment by rinigus** [comment]
geomag should be included in added pure-maps asset.

**Comment by rinigus** [comment]
Closing as stale
