### ISSUE TITLE
Voices 

### ISSUE THREAD

**Issue by elkiaer-dk** [rinigus/pure-maps#599]
I have a XA2 Ultra with SFOS 4.4.0.58.
I have installed Mimic but Voice is not working.

**Comment by okruhliak** [comment]
Voice navigation also doesn't work here:
Gemini PDA SFOS 4.4.0.58, upgrade OTA
PureMaps 3.0.0-1.5.1.jolla, 
Mapbox GL QML Plugin 2.0.1-1.3.1, 
Maplibre GL Native Qt 0.0.220220.3-1.2.1.jolla, 
Mimic 1.2.0.4-1.2.1.jolla
Voice navigation language: English (United States).
When start navigating the route, receive the error message: "Voice guidance is not available. Text to speech (TTS) engine is missing for the selected language".
The voice also doesn't work in the Settings/Testing section.

On Xperia X dual SIM, SFOS 4.3.0.15,
PureMaps 3.0.0-1.5.1.jolla, 
Mapbox GL QML Plugin 2.0.1-1.3.1, 
Maplibre GL Native Qt 0.0.220220.3-1.2.1.jolla, 
Mimic 1.2.0.4-1.2.1.jolla
voice navigation works  (note: the test voice in Settings/Testing works, but first you need to change the language to a different one from the default English and then return it to English).

**Comment by rinigus** [comment]
This is probably due to sailjail lacking some app execute permissions. I haven't updated to SFOS 4.4 yet, would have to work on the port for that first. If you can adjust permissions, find which ones are needed and test the changes, please submit PR

**Comment by okruhliak** [comment]
I was unable to configure permissions for PureMaps to work properly. I tried the parameters sequentially up to: Audio; Location; Sensors; UserDirs; Privileged.
They only work properly with the parameter Sandboxing = Disabled, sorry.

**Comment by rinigus** [comment]
I will look then into it after I finish SFOS update on my port

**Comment by rinigus** [comment]
Fixed in upcoming Chum version. Impossible for Jolla Store...
