### ISSUE TITLE
Instructions for offline usage

### ISSUE THREAD

**Issue by AgentSmith0** [rinigus/pure-maps#600]
Any instructions for how to setup offline usage would be nice to have.

**Comment by rinigus** [comment]
Agreed. Should be done as a part of #400. So far, nobody volunteered to create it.

**Comment by AgentSmith0** [comment]
I have not found any functionality to download regions? Does offline usage only work using cached tiles, that have been used before?

**Comment by rinigus** [comment]
No, cached tiles are mainly side effect. For real offline support, install OSM Scout Server in addition to Pure Maps. See https://rinigus.github.io/osmscout-server/en/ for description. With the server installed, download maps in the server and keep it running. Then Pure Maps can be switched to offline mode and it will get data from server.

**Comment by AgentSmith0** [comment]
Thank you very much! With the instructions offline usage works very well. I hope I will be able to contribute to this project in the future.
