### ISSUE TITLE
Offline routing/search

### ISSUE THREAD

**Issue by programmin1** [rinigus/pure-maps#609]
It seems the routing always fails if no wifi and internet. This would be very useful as in OsmAnd app to work offline!

**Comment by jonnius** [comment]
For offline navigation to work, you need OSM Scout Server installed and running with Maps downloaded. On which OS are you using Pure Maps?

**Comment by programmin1** [comment]
Librem 5

**Comment by rinigus** [comment]
Have you installed OSM Scout Server and do you use Pure Maps offline profile. Instructions at https://rinigus.github.io/osmscout-server/en/

**Comment by rinigus** [comment]
Closing as there is no reply and probably offline server was not used. Reopen if needed
