### ISSUE TITLE
nothing provides 'pyotherside-qml-plugin-python3-qt5 >= 1.5.1' needed by the to be installed harbour-pure-maps

### ISSUE THREAD

**Issue by bszente** [rinigus/pure-maps#612]
### Setup

* Sony Xperia 10 III, Sailfish OS 4.4.0.64
* sailfishos-chum-gui 0.5.0-1.6.2.jolla

### Steps to reproduce

* Select Install Pure Maps in Chum GUI (harbour-pure-maps version 3.1.0-1.6.2.jolla at the moment of writing)

### Expected behavior

Pure Maps should be installed succesfully.

### Current behavior

A notification appears with the following message:

> _nothing provides 'pyotherside-qml-plugin-python3-qt5 >= 1.5.1' needed by the to be installed harbour-pure-maps_

Pure Maps cannot be installed from SailfishOS:Chum GUI.

**Comment by rinigus** [comment]
Please try running `pkcon refresh` from terminal, probably as root (devel-su).

**Comment by bszente** [comment]
> Please try running `pkcon refresh` from terminal, probably as root (devel-su).

Yes, that fixed the problem. Thank you!

**Comment by rinigus** [comment]
Excellent! That magic command never fails :)

**Comment by bszente** [comment]
> Excellent! That magic command never fails :)

I wonder why is it required and not done automatically by package managers :D After years of Sailfishing this was the first time for me to perform this command.
