### ISSUE TITLE
Can't install pure-maps via chum

### ISSUE THREAD

**Issue by flossgeek** [rinigus/pure-maps#615]
I have tried it both via the chum-gui and the chum-cli, but both give the following error:
`Fatal error: the to be installed harbour-pure-maps-3.1.0-1.6.2.jolla.aarch64 requires 'mapboxgl-qml >= 2.0.0', but this requirement cannot be provided`
I've tried `pkcon refresh` as recommended in another [issue](https://github.com/rinigus/pure-maps/issues/612), but this doesn't help either. Sometimes it even gives the following error when trying to install pure-maps again: `Fatal error: couldn't find package`.
I'm on SailfishOS 4.4.0.64 with chum version 0.5.0 (according to the GUI).

**Comment by rinigus** [comment]
I wonder if you uninstalled all mapbox related libs from device first? Such as the ones installed from OpenRepos.

**Comment by flossgeek** [comment]
Yes, that was the problem. Thanks!
