### ISSUE TITLE
Support for opening gpx files

### ISSUE THREAD

**Issue by ehdis** [rinigus/pure-maps#621]
Unable to find downloaded gpx files. An option is to allow access to Downloads (see patch snippet).
A more specific location would be more appropriate but at least a location must exists to be able to load data into the application. 

```
--- harbour-pure-maps.desktop
+++ harbour-pure-maps.desktop
@@ -9,6 +9,6 @@
 BackupPathList=.config/io.github.rinigus/PureMaps
 
 [X-Sailjail]
-Permissions=Internet;Location;Audio
+Permissions=Internet;Location;Audio;Downloads
 OrganizationName=io.github.rinigus
 ApplicationName=PureMaps
```

**Comment by rinigus** [comment]
Please submit it as PR against the desktop file used for Jolla Store version. Note that Chum version shouldn't have this limitation.

**Comment by mschilli87** [comment]
@ehdis:

Thx for reporting and suggesting a fix.

@rinigus:
> Please submit it as PR against the desktop file used for Jolla Store version.

Done: #632.

> Note that Chum version shouldn't have this limitation.

I see Pure Maps as installed and not updatable in Chum and experience this issue regardless.
