### ISSUE TITLE
Foursquare not working (anymore)

### ISSUE THREAD

**Issue by Yomark1** [rinigus/pure-maps#622]
When doing a foursquare search(nearby or best, for example Restaurant) it doesn't return any results.
Error shown when starting pure maps from terminal:
```
unknown:0 - Using QSGMapboxGLTextureNode for map rendering. devicePixelR
atio: 1
Establishing connection to api.foursquare.com
GET failed: Exception: Server responded 410: 'Gone'
Nearby failed:
Traceback (most recent call last):
File "/usr/share/harbour-pure-maps/poor/guide.py", line 121, in nearby
x, y, results = self._provider.nearby(query_type, query_name, near, radi
us, params)
File "/usr/share/harbour-pure-maps/guides/foursquare.py", line 134, in nea
rby
results = poor.http.get_json(url)
File "/usr/share/harbour-pure-maps/poor/http.py", line 232, in get_json
return _request_json("GET",
File "/usr/share/harbour-pure-maps/poor/http.py", line 327, in _request_js
on
text = _request(method, url, body, encoding, retry, headers)
File "/usr/share/harbour-pure-maps/poor/http.py", line 258, in _request
return thread_pool.request(method=method, url=url, body=body,
File "/usr/share/harbour-pure-maps/poor/http.py", line 213, in request
if 'exception' in result: raise result['exception']
File "/usr/share/harbour-pure-maps/poor/http.py", line 166, in _request_wo
rker
result = _request_real(method=task['method'], url=task['url'],
File "/usr/share/harbour-pure-maps/poor/http.py", line 293, in _request_re
al
raise Exception("Server responded {}: {}".format(
Exception: Server responded 410: 'Gone'
```

I validated ClientID and Client secret in settings.

**Comment by rinigus** [comment]
Would you mind to try again? I have just tested and it all worked. Maybe there was some issue with the service?

**Comment by Yomark1** [comment]
Hello Rinigus,

Tnx for the response. Still doesn't work.
Deleted my 'project' at developer.foursquare.com, and created a new one. Copied clientID and secret(doesnt need the API key right?), but still the same issue.
It does seem to fetch the POI types(like many types of restaurants), but after selecting that no results.

**Comment by rinigus** [comment]
Thanks for checking! I cannot reproduce it and I wonder if they are limiting access to some API by (newer) keys? Maybe there was some API update and I am using an old one. Would need to look into it.

**Comment by Yomark1** [comment]
It seems that there are other issues on my x10 III(which I started using three weeks ago) with Pure Maps.
Stadia routing(mapquest open works fine) also doesn't work, but i also didn't specify a API key for stadia(didn't need it before on my old x10). `aultuser@Xperia10III ~]$ harbour-pure-maps
Current locale: nl_NL
Loaded translation
[D] unknown:0 - Using Wayland-EGL
library "libGLESv2_adreno.so" not found
library "eglSubDriverAndroid.so" not found
library "vendor.qti.qspmhal@1.0.so" not found
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/li
bpyothersideplugin.so"
[I] unknown:0 - Acquired QGeoPositionInfoSource: "geoclue"
[D] unknown:0 - Tracking  "io.github.rinigus.OSMScoutServer"
[W] unknown:0 - QConnmanTechnologyInterface::scanReply() "No carrier"
[W] unknown:71 - file:///usr/share/harbour-pure-maps/qml/PositionSource.qml:
71: TypeError: Cannot read property 'center' of null
[D] onCompleted:580 - Warning: specifying an object instance for initialPage
is sub-optimal - prefer to use a Component
[D] unknown:0 - Geoclue client path: "/org/freedesktop/Geoclue/Master/client
5"
[W] unknown:91 - file:///usr/share/harbour-pure-maps/qml/pure-maps.qml:91:5:
QML PositionSource: Binding loop detected for property "active"
[W] unknown:0 - Positioning update timeout
[W] unknown:0 - Translation not found for navigator: "en"
Started DBus service at io.github.rinigus.PureMaps
[D] init:78 - Initializing voice engine navigator en male
[D] init:83 - Voice engine: navigator Mimic active=true
[D] init:78 - Initializing voice engine navigator en_US male
[D] init:83 - Voice engine: navigator Mimic active=true
[W] unknown:0 - Translation not found for navigator: "en_US"
[D] unknown:0 - Reset locations true 0 2
[I] unknown:0 - Using QSGMapboxGLTextureNode for map rendering. devicePixelR
atio: 1
[W] unknown:0 - [ INFO ]  "{unknown}[General]: GPU Identifier: Adreno (TM) 6
19"
[W] unknown:169 - file:///usr/lib64/qt5/qml/Sailfish/Silica/DialogHeader.qml
:169: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:164 - file:///usr/lib64/qt5/qml/Sailfish/Silica/DialogHeader.qml
:164: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:224 - file:///usr/lib64/qt5/qml/Sailfish/Silica/DialogHeader.qml
:224: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:219 - file:///usr/lib64/qt5/qml/Sailfish/Silica/DialogHeader.qml
:219: TypeError: Cannot read property 'forwardIndicatorDown' of null
[D] unknown:0 - Prompts reset
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
[W] unknown:57 - file:///usr/share/harbour-pure-maps/qml/RouterPage.qml:57:9
: QML LabelPL: Binding loop detected for property "_elideText"
Establishing connection to route.stadiamaps.com
GET failed: Exception: Server responded 400: 'Bad Request'
Routing failed:
Traceback (most recent call last):
File "/usr/share/harbour-pure-maps/poor/router.py", line 134, in route
route = self._provider.route(locations=locations, params=params)
File "/usr/share/harbour-pure-maps/routers/stadiamaps.py", line 157, in ro
ute
result = poor.http.get_json(url)
File "/usr/share/harbour-pure-maps/poor/http.py", line 232, in get_json
return _request_json("GET",
File "/usr/share/harbour-pure-maps/poor/http.py", line 327, in _request_js
on
text = _request(method, url, body, encoding, retry, headers)
File "/usr/share/harbour-pure-maps/poor/http.py", line 258, in _request
return thread_pool.request(method=method, url=url, body=body,
File "/usr/share/harbour-pure-maps/poor/http.py", line 213, in request
if 'exception' in result: raise result['exception']
File "/usr/share/harbour-pure-maps/poor/http.py", line 166, in _request_wo
rker
result = _request_real(method=task['method'], url=task['url'],
File "/usr/share/harbour-pure-maps/poor/http.py", line 293, in _request_re
al
raise Exception("Server responded {}: {}".format(
Exception: Server responded 400: 'Bad Request'
[D] unknown:0 - Geoclue client path: "/org/freedesktop/Geoclue/Master/client
6"
[W] unknown:0 - Positioning update timeout
[W] unknown:91 - file:///usr/share/harbour-pure-maps/qml/pure-maps.qml:91:5:
QML PositionSource: Binding loop detected for property "active"`

**Comment by rinigus** [comment]
Any progress with this? Or it is still the issue for you with Foursquare?

**Comment by rinigus** [comment]
Closing as stale

**Comment by brammiddendorp** [comment]
I am experiencing the same issue.
It occurred to me that Pure Maps is still expecting a Client ID and Client Secret, which belong to the legacy OAuth Authentication method of Foursquare. Newly created keys however only consist of a single string. Perhaps new accounts will therefore not work with the (legacy) OAuth Authentication method?
