### ISSUE TITLE
Allow voice navigation with display off

### ISSUE THREAD

**Issue by Pohli** [rinigus/pure-maps#63]
Some days ago I used Pure Maps on a bike but don't have a holder for my Jolla Phone. So I started navigation, connected headphones and put the phone into my pocket. It worked but the screen was still turned on unnecessarily lowering battery. How about a "pocket mode" where you can still hear directions but the screen is turned off?

**Comment by rinigus** [comment]
Makes sense, let's keep it in the list

**Comment by rinigus** [comment]
Renamed the issue to trigger easier discovery

**Comment by Olf0** [comment]
Yes, please!

I tried the same as @pohli and @Arvedui when navigating by foot in a foreign city (headset on, phone in the pocket), which renders PureMaps navigation useless.

Actually issue #104 provides a more concise description of the issue:
PureMaps' navigation stops, when the screen saver becomes active.

The workaround to deactivate the screen saver temporarily, wastes a lot of battery uselessly and is dangerous (screen & touch active in ones pocket).

P.S.:
Furthermore PureMaps stops polling GPS / GNSS when the screen saver becomes active, in contrast to e.g. GPSinfo.
Consequently after each screen unblanking, a fresh position fix has to be obtained to display ones correct location; until then PureMaps uses some old, stale location data (i.e. displays an incorrect position).  This may or may not be what PureMaps receives by the location API, but keeping GNSS continuously alive would eliminate this irritating effect.
Workaround: Let GPSinfo run in parallel to PureMaps.

**Comment by rinigus** [comment]
I guess we do need such mode which will keep GPS fix and device awake while keeping screen off. Its just has to be done correctly to ensure we don't drain batteries without user's knowledge. There was an interested developer at TMO, let's see if something resurfaces. I have a short break from Pure Maps (1-2 weeks) planned, later will continue on it.

**Comment by rinigus** [comment]
Implemented and will be a part of the next release
