### ISSUE TITLE
"Legal issue" link for HERE has moved

### ISSUE THREAD

**Issue by phs** [rinigus/pure-maps#633]
On the license accept page for HERE api integration, the mentioned "legal issue" link is https://knowledge.here.com/csm_kb?id=public_kb_csm_details&number=KB0016412

This appear to have moved to here: https://knowledge.here.com/csm_kb?id=public_kb_csm_details&number=KB0017825

**Comment by rinigus** [comment]
Thanks for pointing it out. I wonder why they move it around ...

**Comment by rinigus** [comment]
Fixed in 23bbf5a
