### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by programmin1** [rinigus/pure-maps#634]
Will this project be participating in Hacktoberfest this year?
If you add Hacktoberfest topic on the repo, then folks will probably find this repo and work on it or try to fix bugs over this next month.

**Comment by rinigus** [comment]
I haven't ever tried to participate in it. Could be fun - let's hope I have time to respond timely.

**Comment by rinigus** [comment]
... coming back to your question - don't know. Would have to select issues that are self-contained.

**Comment by rinigus** [comment]
Closing as it expired.
