### ISSUE TITLE
Sailfish 0S 4.4 Pure maps language issue

### ISSUE THREAD

**Issue by Thermo41** [rinigus/pure-maps#643]
Hi

On a sailfish OS 4.4.0.72 / Pure maps 3.1.0-1 / Xperia 10 II i.e. 64 bits, I have an issue :

- the use of French/female voice does not work, the system says no engine supports that
- however I have picotts (pico2Wave) installed version 17.10.1-1.2.1.jolla  , 
both are installed out of Chum. 
However
- Pico2Wave supports French/female
- When I look at pure maps /usr/share/harbour-pure-maps/poor/voice.py, I see that pico2ware is known supporting french female.
- eventually, in Test, it says no engine available for selected language systematically  for any language/gender I can try.

I have not yet investigated any further and will hardly have time in the next two days. I will try later on and will let you know if I find anything.
If you have any opportunity to look at what is happening, then I would be glad.

Regards
Dominique

**Comment by rinigus** [comment]
Same as #650 . Please see that issue and I will have to think how to make it clearer.

Sorry for late reply. Closing here
