### ISSUE TITLE
TTS working with default profile, but broken with HERE

### ISSUE THREAD

**Issue by JacekJagosz** [rinigus/pure-maps#647]
I am using Pure Maps from Chum on SFOS 4.5, Xperia 10 III, system language is Polish, map language set to local.
I have Mimic installed, testing it from the settings works, also when you start navigation in the default online profile it works just fine too, the voice language is English.
But when I switch the profile to "HERE - online" and I try to start the navigation I get an error:
![Zrzut_ekranu_20230204_001](https://user-images.githubusercontent.com/28653965/216778881-a13cfa03-d155-4c3c-a309-ee65e4e3ab56.png)
It says "Route found. Navigation started. No TTS engine for chosen language". Which is weird, because when I change the profile back to online the TTS will work just fine. I thought it could be the fact that Here for some reason tried to use Polish language, so I changed the map language to English, but it didn't change anything.

**Comment by rinigus** [comment]
Routing instructions are set for each provider separately. Check which language do you have in "HERE - online" for routing. For that, press Route button and check in the appearing dialog what is the language for instructions. Such setting location is due to the differences in routing providers - HERE has options which are different from other providers.

**Comment by JacekJagosz** [comment]
How can I force the Here language to English then? Because even when I set the map Language to English, the instructions are still in Polish. While with Online profile they simply are in English.

**Comment by rinigus** [comment]
I think you are setting the language in the different place. To set routing instructions to English:

- activate HERE online profile
- Click on 9-dot main button
- From the app main menu, select Navigation
- In navigation dialog, Choose where do you want to route
- In navigation dialog, after you entered the target (To), options should appear below
- In navigation dialog, choose English language from options
- In navigation dialog, calculate route

Let me know if it helped or you already tried that

**Comment by JacekJagosz** [comment]
Thank you a lot! I searched for this setting in the preferences, or in the navigation menu, but before I selected the destination.
But the place it is right now makes sense, I just didn't think about it. Thank you!

**Comment by rinigus** [comment]
Yes, navigation dialog was made simple before you select the target. Otherwise, it was very overwhelming... Great it all worked out.
