### ISSUE TITLE
Street numbers when entering destination

### ISSUE THREAD

**Issue by BurnyBoi** [rinigus/pure-maps#652]
When entering a destination, I can't seem to enter the street number. When including the street number in my search, it will return the street without the number as an option for the destination.

**Comment by rinigus** [comment]
This would depend on which map provider do you use and whether the map data has street and number linked. Which provider did you use? If OSM, try to check if search at osm.org finds your place.

**Comment by BurnyBoi** [comment]
Under the Search page for destination, I pressed "..." followed by Change Provider and changing from Photon to OpenCage has gotten street numbers showing in the search. Thanks!

**Comment by mburucuyapy** [comment]
I have the same issue, but both Photo and and OpenCage give the same result. I always have to put the street name first and then the house number and not the other way around
