### ISSUE TITLE
Cannot assign to non-existent property "onMapToQtPixelRatioChanged"

### ISSUE THREAD

**Issue by Skoll444** [rinigus/pure-maps#658]
When starting the Pure Maps client, a white client window appears, and this is the error. Any ideas how this can be fixed?
operating system: Ubuntu 20.04
Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
Acquired QGeoPositionInfoSource: "geoclue2"
Calculate direction using a sequence of coordinates
Tracking  "io.github.rinigus.OSMScoutServer"
QQmlComponent: Component is not ready
file:///usr/local/share/pure-maps/qml/platform/ApplicationWindowPL.qml:47:5: QML StackView: replace: file:///usr/local/share/pure-maps/qml/RootPage.qml:34 Type Map unavailable
file:///usr/local/share/pure-maps/qml/Map.qml:345 Cannot assign to non-existent property "onMapToQtPixelRatioChanged"
Service appeared  "io.github.rinigus.OSMScoutServer"

**Comment by rinigus** [comment]
Sounds like Mapbox GL QML plugin is not updated in your distribution (see #654). Or, if you installed it yourself, please update by installing new:

- Maplibre GL Native
- Mapbox GL QML

See the issue that I referred to above for background and specific versions.

**Comment by Skoll444** [comment]
If you can help me figure it out, I'd appreciate it. 
I installed the [module](https://github.com/rinigus/deb-qml-module-mapboxmap/) follows:
1)  First of all, I installed https://github.com/rinigus/pkg-mapbox-gl-native branch (gcc-regular) . Maybe I need a qt or sfos branch, but I don't see how I can do it. What mean "upstream for packaging QMapboxGL library directly in the other systems?"
2) After installing pkg-mapbox-gl-Native, I was able to install the [mapbox module](https://github.com/rinigus/mapbox-gl-qml) without errors.
3)Nowhere during the installation was the MapLibre library required. Do I need it? and how to install it?
Thank you for your time

**Comment by rinigus** [comment]
Which version of https://github.com/rinigus/mapbox-gl-qml did you install? 2.1.1?

Instead of Mapbox GL Native, install Maplibre GL Native from https://github.com/maplibre/maplibre-gl-native/releases/tag/qt-v2.0.1

**Comment by Skoll444** [comment]
You're right, the version of my module was very old.
I installed [deb-qml-modulemapboxmap](https://github.com/rinigus/deb-qml-module-mapboxmap/blob/master/source_install.md?ysclid=lftmyrzslt723524477) instead of [mapbox-gl-qml](https://github.com/rinigus/mapbox-gl-qml).
Can you please explain how to install the library [Maplibre GL Native qt-v2.0.1](https://github.com/maplibre/maplibre-gl-native/releases/tag/qt-v2.0.1)?
I've been trying for the second day, but I can't understand.
I understand that I have to create a library "QMapLibreGL" To install Mapbox-gl-qml.
The only thing I get as a result of building the Maplibre GL Native library is "mbgl-benchmark-runner" "mbgl-render-test-runner" "mbgl-test-runner".
And last question Do I need to follow the mapbox-gl-qml installation [instructions](https://github.com/rinigus/mapbox-gl-qml/blob/master/source_install.md) , It seems to me that it is no longer true, then what should I do now?

**Comment by rinigus** [comment]
Re Maplibre Native GL: you have to install it from source. Example compilation see at https://github.com/rinigus/pkg-maplibre-gl-native/blob/master/rpm/maplibre-gl-native.spec#L60 . Just replace %cmake with cmake and run make -jXX after that:

```
cmake -DMBGL_WITH_QT=ON -DMBGL_WITH_WERROR=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DMBGL_QT_WITH_HEADLESS=OFF -DMBGL_QT_LIBRARY_ONLY=ON -DMBGL_QT_STATIC=OFF -DMBGL_QT_WITH_INTERNAL_ICU=ON .
make -j8
make install
```

Re QML plugin install instructions: yes, its switched to cmake:

cmake
make -j8
make install

**Comment by Skoll444** [comment]
Thank you very much, it helped)

**Comment by rinigus** [comment]
Thank you for working on it! You are welcome to submit documentation updates to make it easier for others (and you) in future :)
