### ISSUE TITLE
Use USB GPS device as source (Linux)

### ISSUE THREAD

**Issue by AgentSmith0** [rinigus/pure-maps#660]
Hello, is it possible to use a USB GPS receiver as source for getting the current position? I get position data using gpsd, but not via geoclue.

**Comment by rinigus** [comment]
It probably can. That you have to discuss with your OS maintainers. They probably know already what's the next step

**Comment by hellkaim** [comment]
@AgentSmith0 Why don't you use that: `gpsd -D 5 -N -n /dev/ttyACM0`? That will proove you can see the GPS data.
After that it may be [this answer](https://stackoverflow.com/a/59570084) that can help.

According to the [GeoClue git](https://gitlab.freedesktop.org/geoclue/geoclue/-/tree/master/src) it seems that modems are supported. The only thing left is to how to explain it to your Linux.

In

**Comment by rinigus** [comment]
Closing here as it is out-of-scope for Pure Maps to start supporting positioning providers directly. Please solve it on Qt level and make available for all apps.

**Comment by k8ieone** [comment]
@AgentSmith0 I have a perfectly working setup using a Meshtastic device. Any device that outputs NMEA data over serial should work.

Don't bother with gpsd, it is **not** being used by Pure Maps *or* Geoclue.

More info: https://github.com/meshtastic/firmware/issues/6731#issuecomment-2849326121
