### ISSUE TITLE
How do you turn on location?! 

### ISSUE THREAD

**Issue by triplemaya** [rinigus/pure-maps#662]
There is no location marker! How do you turn on location? Cannot find ANYTHING in settings. Bit frustrated!

**Comment by rinigus** [comment]
You have to enable location on the system level. Then Qt will trigger GPS automatically when you use Pure Maps. Now how to enable location on system level would depend on your device and its OS. If in Sailfish, its system settings or maybe in your phone shortcuts to them.

**Comment by triplemaya** [comment]
Hi. Thanks. Got it. Many thanks. Confused because uNav seemed to get it automatically. 
Also confused because uNav has a sign at the top of the screen saying GPS waiting. And it takes ages unless I put it by the window. But nothing like that in pure that I can see. It just does not work. Then eventually it does.
