### ISSUE TITLE
unnecessary confusing turns

### ISSUE THREAD

**Issue by Kuba77cz** [rinigus/pure-maps#665]
Sometimes during navigate, it shows these unnecessary turns. This was in Kobylnice near Kutná Hora in Czechia, but I saw it many times in Czechia and Poland, I just didn't have time to take screenshot.
![Snimek_20230407_002-](https://github.com/rinigus/pure-maps/assets/18407160/8c077925-05f6-4cb6-bc19-884d4134438d)

**Comment by rinigus** [comment]
Pure Maps is, in this context, mainly a client for router. So, it could be due to router. However, in this case, you may have missed intermediate destination and tries to route you back to it.

**Comment by rinigus** [comment]
Unless shown it is Pure Maps bug, closing it here. Feel free to comment and discuss the issue after it is closed.
