### ISSUE TITLE
Add support for different platforms

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#73]
Right now Silica is incorporated into main QML code. Split Silica from the rest to allow to support other platforms

**Comment by rinigus** [comment]
Will have to figure out what to do with 

page.status, onStatusChanged, onStatusChanged, PageStatus.Activating, Active

**Comment by spaetz** [comment]
If icons are generic, abstracting sth from https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html could be useful? or are these application specific icons?

P.S. Looking forward to using puremaps on a desktop and the librem by the way 😃.

**Comment by rinigus** [comment]
Thanks for the pointer! I'll look into it.
