### ISSUE TITLE
Automatic adjusting of the scale

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#76]
From https://talk.maemo.org/showpost.php?p=1549254&postcount=239

Automatic adjusting of the scale, based on vehicle speed and/or type of road and/or distance to next turn/exit/merge.
In city, being able to see close street-crossing details is helpful, whereas on high speed highways, being able to see further down the road is useful.
After-market satnavs (like Tomtom, Garmin) tend to do something along these line, which is useful given that there's no way to quickly change scaling using some on-steering-wheel command (unlike in-car built-in satnav, which could use the on-steering-wheel mouse-wheel-like selector).

**Comment by rinigus** [comment]
Let's take time as a regulator for zoom adjustments. so, zoom will change with speed in accordance with time needed to go to cover some distance

**Comment by planetos** [comment]
An auto-zoom feature would be a great improvement. Maybe even add some sliders for personal manual adjustments in Settings? Other than above there are some useful considerations on that page: https://help.locusmap.eu/topic/auto-zoom-levels

**Comment by rinigus** [comment]
Thank you for the reference, will look into it when I start working on this issue

**Comment by rinigus** [comment]
Sorry, wrong issue referred to. Reopening

**Comment by rinigus** [comment]
Implemented, closing
