### ISSUE TITLE
QtCreator project

### ISSUE THREAD

**Issue by accumulator** [rinigus/pure-maps#97]
Would you be interested to use a QtCreator .pro file for building pure-maps, instead of the current handcrafted Makefile? I see a few advantages;

- lower barrier to entry for new developers, as they would be able to much easier clone, build and test the app
- more rapid development by using QtCreator (QML) debug or even QmlLive functionality
- better maintainable, because of less scripting 
- more portable

I'm willing to tackle this, if you're open to it.

**Comment by rinigus** [comment]
I think its a great idea! It would simplify coding for all of us. Just few things to keep in mind:

* we should probably get the projects for each platform separately
* projects should have uniform part that is for all platforms the same and included automatically into each platform (something like include?)
* somehow, procedures covered in RELEASING should be supported

Note that translations are handled by PO files. Not sure how to incorporate that into such project file. Maybe we should also consider having Makefile for the misc procedures (make check, test, ...) and Qt project files for building RPM/DEB/...?

**Comment by accumulator** [comment]
Great!

> we should probably get the projects for each platform separately

agreed.

> projects should have uniform part that is for all platforms the same and included automatically into each platform (something like include?)

Yes, as much as possible. I think the translations might need some special attention here, taking care not to duplicate strings.

> somehow, procedures covered in RELEASING should be supported

Yes, however I think there is a split there. Release preparation is a maintainer task (e.g. update translations from transifex, updating changelog etc), and these steps maybe not easy to include in the project file/Makefile. The tests, checks and key inclusion should though, IMO.

RPM/DEB/flatpak target building is a bit in between. The Sailfish SDK builds the RPM itself, without help from any declarations within the project file. This can be supported through scripts, which might be possible to support from the project file. Not sure yet where this would land..

**Comment by rinigus** [comment]
Question is whether we are planning to get QMAKE or CMAKE projects. I have not worked with CMake much so far.

I don't know how other Python-only projects build RPMs. Note that its great to have an ability to build RPM from regular Linux. This I would like to keep - its way easier than SFOS SDK. Also, it would be great to have SFOS project that we can open in regular Creator. 

In this regard, maybe we should keep projects minimal and keep "maintainer's" Makefile as well. So, Qt project will only install the code as needed and packages will be generated by running projects' make as well as maintainer's make. Maybe reasonable suggestion and will avoid duplication.

One more alternative - just make project files for editing and not using them for making anything else. For everything else, we have the makefile already. In this case, PRO files could be somewhere in subfolder for keeping root as clean as possible.

**Comment by accumulator** [comment]
See PR #103
