### ISSUE TITLE
Search accessibility

### ISSUE THREAD

**Issue by rinigus** [rinigus/pure-maps#99]
Rephrased from Tobias and the similar issue was raised by Taixzo:

There are too many clicks and interactions required to enter a search string. Right now, it involves:

* click on menu
* click Search
* click on search box 
* type search + Enter
* select result

All this includes menu, search, search result pages. In contrast, Google Maps and HERE: 

* click on search box 
* type search + Enter
* select

With the use of search while you type, frequently you don't have to hit enter in GMaps/HERE. Pure Maps does have same search as you type, but there is still an impression that you have to navigate far from the map before getting somewhere.

Related to #25

**Comment by rinigus** [comment]
When comparing with others:

* HERE and Google Maps essentially replace map view with the search as soon as you press Search box. There is no page stack animation involved, instead animation of elements (Google) or plain replacement (HERE). Search box is selected as well.

Google groups the old searches by dates, which probably helps.

* Maps.me and OsmAnd have a search button on the map which initiates the search by switching into corresponding page.

**Comment by rinigus** [comment]
In search, include POIs (show shortlisted, bookmarked and others, in this order). Search could be used in navigation and nearby pages as well.

**Comment by bertob** [comment]
The google solution (showing a searchbar, and opening recommendations/results over the map when you click it) seems most natural to me, but the maps.me solution could work too, at least as a stop-gap.

I think the most important thing is removing search from the menu, making it accessible with one click from the map view, and having a single-click back button for going back from the search results to the map.

**Comment by rinigus** [comment]
Agree, search should be simply accessible from the main map view. So far, the work was done on making the search page to work as simply as possible. I am planning to hook that page to a single click on an element on a map. That would remove additional nesting of pages as it is now (Map->Menu->Search) to (Map->Search). 

Whether we should position a bar (like google and here) or a button would depend on overall distribution of elements on map view. We would probably need 2 layouts - simplified and full - as suggested in #117 . 

I'll deal with the policy described in tmpPOI issue first and then come back to hooking search to a map element.
